### ISSUE TITLE
New homepage

### ISSUE THREAD

**Issue by fuzzy76** [Smashing/smashing#1]
The fork will probably need its own homepage

**Comment by kinow** [comment]
Perhaps a simple GitHub page, like dashing-io.github.io

**Comment by geoaxis** [comment]
Can people start collaborating on the wiki for the time being? Content can be ported to github page later.

**Comment by maartendamen** [comment]
I'm willing to host/ pay for a domain name. 
Or can we use the existing domain name? Can the new maintainer please contact me?

**Comment by kinow** [comment]
Might be a bit tricky to have a domain name. testanything.org had problems after some years as someone forgot to pay the domain, and no one knew who to contact. One person was given permission to the nano editor, and when there were problems with the project instead of forking he used the web site to host a new version.

Not saying any of this will happen to the dashing project, but I'd be less worried to contribute if I could be sure that the project will be independent. Later if the project gets bigger (and hopefully it will), we can move it under FSF like Jenkins (https://directory.fsf.org/wiki/Jenkins) or create a group like a foundation, as in the Node project (https://nodejs.org/en/foundation/).

@maartendamen what do you think if we keep using GitHub for now, during the migration from the old project under this GitHub org?

I'm +1 for either setting up a quick Jekyll template and using GitHub pages, or start using the Wiki as @geoaxis suggested.

**Comment by pushmatrix** [comment]
Hey guys. Shopify will be keeping the `dashing.io` domain for the time being so people can still use and refer to the project as-is. Personally, I'd go the github.io route for this fork.

**Comment by kinow** [comment]
So with the project new name (smashing) I think dashing.io won't be used in the future. Could not see when dashion.io expires through whois. But I think we can start working with GitHub pages now.

The org name is SmashingDashboard. So the web site would be https://smashingdashboard.github.io. And we would have to create a repository called smashingdashboard under that organization.

Or we could rename the organization to Smashing and just add GitHub pages to the existing smashing repository (as it would serve the content for smashing.github.io). Thoughts?

**Comment by tylermauthe** [comment]
I couldn't name it Smashing as that Org name was taken. I would much prefer it to be named Smashing though.

GitHub pages would be awesome.

**Comment by kinow** [comment]
Organization renamed @tylermauthe. Thanks to the GitHub team :-) the user name was not taken, though I think it was used in the past.

Will update the gh-pages branch. You can go to the page http://smashing.github.io/smashing/ and see the old web site. Will try to first update it so that http://smashing.github.io/ displays that web site. Then update name, links, etc.

:+1:

**Comment by tylermauthe** [comment]
Woot!

**Comment by tylermauthe** [comment]
I did some basic renaming here:
http://smashing.github.io/smashing/

There are more improvements that could be made though. Would also like to see an org wide page for sure...

**Comment by geoaxis** [comment]
Neat stuff.

Where is the repo for the site though?

I would like to help with some pull requests (starting with cleaning up
references to Shopify)

--
Hatim

--
Shahzada Hatim

**Comment by kinow** [comment]
@geoaxis the same repository of the project, but you have to use the branch gh-pages

https://github.com/Smashing/smashing/tree/gh-pages

**Comment by tylermauthe** [comment]
@geoaxis I'm curious what references you're going to remove... The homage to Dashing, which states this is a fork of Dashing should not be removed. The copyright at the bottom cannot be removed until we redesign the page entirely.

We should do the latter, but I don't really want to deny our heritage... Especially not until we've made more substantial changes to warrant that disconnect!

**Comment by geoaxis** [comment]
@Bruno
Ah, didn't check the branch.  Thanks

@Tyler
Ofcourse, we must attribute where applicable.

Well copyright on index needs to be changed (as you pointed out). We can
not change the page and force the copyright onto Shopify (unless that is
what Shopify has requested)

Also Shopify name in the MIT license.

--
Hatim


--
Shahzada Hatim

**Comment by tylermauthe** [comment]
@geoaxis Great points! Well said. Thanks!

**Comment by JoshuaEdwards1991** [comment]
Hey everyone! great work on this project its great! Hopefully I contribute one day! I was wondering if you still use the dashing generator commands when scaffolding the project? such as dashing generate dashboard name

**Comment by dvinciguerra** [comment]
+1

**Comment by dvinciguerra** [comment]
Smashing Dashboard website layout proposal (only cover, work in process)... sugestions are welcome! :)

![smashing-cover](https://cloud.githubusercontent.com/assets/114177/24732441/609ec6ae-1a47-11e7-8241-8de2d62785c6.png)

**Comment by markwooff** [comment]
Looks great! Would love to see this as the new home page.

**Comment by tylermauthe** [comment]
I absolutely love that design! More please!

**Comment by dvinciguerra** [comment]
Thank you! :)

**Comment by dvinciguerra** [comment]
New version of website homepage... again, suggestions are welcome!
![smashing-home](https://cloud.githubusercontent.com/assets/114177/24821027/9d84ef40-1bc2-11e7-8fe2-e33055ebc180.png)

**Comment by kinow** [comment]
I like it! The search widgets, not sure what it would use to search them. Maybe instead it could be a list of some popular widgets, and a text saying that there are heaps of other widgets available.

As a side note, I've been planning to start a separate thread to add screen shots to all widgets in the same page they are listed in the Wiki. Might plan to finish this when we have the new web site, to use the momentum :-)

Thanks

**Comment by dvinciguerra** [comment]
Cool @kinow.  :)
The widget screenshots is a really great idea!

My idea when I think about a search "page" for widgets is to make easy for smashing users found an specific widget... something like Middleman extensions at this link:
https://directory.middlemanapp.com/#/extensions/all

Then we could use the screenshots to illustrate how to this widgets works. What do you think!?

Thanks for you comment by the way! :)

**Comment by dvinciguerra** [comment]
A new version of smashing homepage proposal...
![smashing-home](https://cloud.githubusercontent.com/assets/114177/24824650/b0fa7aae-1be5-11e7-952d-ac18dc8a4391.png)

**Comment by kinow** [comment]
I like the idea of a search box. The only issue is that we don't have any index file, or web service to search for widgets.

+1 for the updated design. Thanks!!!

**Comment by dvinciguerra** [comment]
Working at http://bivee.com.br/open-source/smashing/index.html.
Is there a git repository that I can submit a PR to?

**Comment by kinow** [comment]
Right now the web site is at https://github.com/Smashing/smashing/tree/gh-pages

However, we may create smashing/smashing.github.io. This way users won't have to type smashing.github.io/smashing, but simply smashing.github.io. WDYT @tylermauthe ?

**Comment by kinow** [comment]
If there is no objection, I will create a smashing.github.io repository tomorrow, and will deploy the contnet from the gh-pages website there. @dvinciguerra in that case, you would be able to submit your pull request there.

**Comment by kinow** [comment]
Also protected the current gh-pages branch in this repo, to prevent incorrect updates happening here :-)

**Comment by dvinciguerra** [comment]
Thanks @kinow :)

**Comment by tylermauthe** [comment]
Thanks @kinow and @dvinciguerra! You guys rock.

I'd love to get the new designs onto the new site and start linking to that everywhere. Cheers!

**Comment by kinow** [comment]
Indeed @tylermauthe ! @dvinciguerra if you submit a pull request to the new smashing.github.io repository, we can review, merge, update the site :)

**Comment by dvinciguerra** [comment]
@kinow and @tylermauthe...

I working on the new version of homepage in a forked repository...
... and I'm using jekyll (with sass and coffee) as a SSG to develop the new version.

Follow this repository to more news about the dev process:
https://github.com/dvinciguerra/smashing.github.io

Best,

**Comment by dvinciguerra** [comment]
Almost done.... 
...but a little bit different from my wireframe sketch! :S

![screenshot-2017-7-20 smashing the spiritual successor to dashing](https://user-images.githubusercontent.com/114177/28441507-8c7f30b4-6d81-11e7-9c9d-4e8d92ffd488.png)

Is it ok? Any comment?

Best,

**Comment by DandyDev** [comment]
This looks awesome! Why hasn't this been merged yet?

**Comment by RonanC** [comment]
When is this getting merged in?
The UI mockup is beautiful and modern.
PUSH THE BUTTON :)

**Comment by dvinciguerra** [comment]
@RonanC thanks! I fixed last week some UI and Jekyll issues. At now the new website implementation is able to be merged. I will submit today a PR.

**Comment by dvinciguerra** [comment]
PR submitted https://github.com/Smashing/smashing.github.io/pull/2

**Comment by kwent** [comment]
I think this PR could be closed :)

**Comment by kinow** [comment]
Thanks @kwent, you are correct. PR was submitted and merged. Closing now.
