### ISSUE TITLE
Can An Upgrade Adapter Be Built For Batman.js Components?

### ISSUE THREAD

**Issue by tylermauthe** [Smashing/smashing#10]
Batman.js is deprecated, it should be replaced. However, there are a ton of excellent Dashing widgets that are written in Batman.js and would be deprecated. This would be a huge hit to the ecosystem, so it has been avoided.

With the fork of the project and new energy I feel building behind it, I think it would be prudent to tackle this question as a stepping stone to talking about how and when to replace Batman.js.

I can think of three approaches to this migration:
1. Build, test, and support both Batman.js and `<cool new framework>` components, including dependencies for both libraries. This will be easy up front, but a maintenance hassle forever and ever.
2. Completely drop support for old components. As I said above, I feel this would be a big hit to the ecosystem overall.
3. Build an upgrade adapter that makes legacy components work in the cool new way. Maybe we can slowly deprecate features via this adapter and provide guidance on how to rewrite.

IMHO, the best choice is 3 - if it's possible. Supporting both old and new components will be a real hassle in the long term, though there may be ways to minimize that pain. If we don't support legacy Widgets directly in Dashing, they almost certainly will be hacked back in by someone anyway. If a breaking change is found to be necessary, we're basically re-writing the whole project and should almost certainly rename the project ( #8 ).

So, this issue is to explore whether it's possible to create an adapter and what would be involved in doing that.

**Comment by tylermauthe** [comment]
I will be exploring the possibility of implementing an adapter in React.

To give an idea of what will be involved, any adapter will need to provide the same features of a `Dashing.Widget`, which is a subclass of `Batman.View`. This includes Batman.js Lifecycle events, binding expressions and filter expressions. Many components also use jQuery, providing a shimmed version of jQuery for use in these new components may also be necessary.

A high level description of how this may be done in React:
- loop over props, process each of them as binding expressions if appropriate
- evaluate all the binding expressions and perform any filter expressions
- write shims to support Batman.js' pub/sub mechanisms
- using those shims, emit events for the full Batman.js lifecycle

**Comment by kinow** [comment]
+1 for option #3 (if possible). An abstraction layer taking care would be great!

Don't know much about React (using Backbone and a bit of Angular sometimes), but in case you need someone to review some code or test something, just ping me :+1:

**Comment by tylermauthe** [comment]
After a quick survey of some components in the wiki, the vast majority of components could be supported with a subset of features the above. None of the components I saw made use of Batman.js pub/sub or lifecycle mechanisms.

Very few binding expressions seem to be used (~80% are just `data-view`) and filter expressions are also rare.

I believe that an upgrade adapter that supports the widgets provided in the sample project would likely cover 80% of use cases. I'll work with those for now, I will definitely need guinea pigs as this progresses.

Also, just to clarify the output of this task will be knowledge (and maybe some throwaway code). We're a long ways away from actually replacing Batman.js.

**Comment by kinow** [comment]
>Also, just to clarify the output of this task will be knowledge (and maybe some throwaway code). We're a long ways away from actually replacing Batman.js.

Perhaps we could try to have as output of this task the adapter to Batman.js. Allowing us in the future to deprecate Batman and switch to another library?

**Comment by tylermauthe** [comment]
Couple reasons: I'm not convinced that React is the way to do this, but I really want it to be. I also don't want to do this poorly, so I intend to throw away the code and re-write it with the lessons learned in mind from the beginning.

Hopefully this adapter can act as migration path, allowing Dashing to selectively deprecate legacy support while providing clear guidance to developers. I believe this level of robustness will only be possible with a well thought-out solution.

**Comment by tylermauthe** [comment]
Re-writing Dashing in React, Angular, Vue.js or whatever is easy... And has been tried before. The core of what Dashing does is simple.

Moving the community is hard... And will take finesse and time. That's another, sneakier, reason :wink:.

**Comment by tylermauthe** [comment]
This seems like useful advice: https://discuss.reactjs.org/t/jquery-with-react/683/4

I also had a crazy thought: almost all use of jQuery in the components I saw was done on `@node`. Since those operations would be contained to the scope of the component being described, they could be re-written as React operations. Would it be possible to collect those jQuery operations and translate them to React equivalents? Could this ever be done perfomantly?

**Comment by tylermauthe** [comment]
Started on it here: https://github.com/tylermauthe/dashing-react-adapter

The first major challenge with this seems to be the conceptual differences between the render model of React and the data-binding model of Batman.js.

React wants to know everything about the state of your UI before it does anything to the DOM. Batman.js doesn't do anything until it knows the state of the DOM.

Essentially this means React does not know how to take a tree of DOM elements rendered by the browser and enhance them with logic -- so that is a fundamental blocker to this change.

However, there may be non-ideal workarounds.

We could build a "`Legacy`" component that grabs the HTML rendered by the ERB and then processes it. The HTML could be grabbed on page load and the `Legacy` component would read from that. This would allow React to parse the HTML into React components and then render a list of `Widget` components.

My first goal with this will be to create a Legacy component that grabs HTML and just naively outputs it. Then I will try to parse that HTML into React components and render those instead.

After this, the next hurdle will likely be that the widgets themselves are just simple `div` elements. In React, this will mean overriding the built-in `div` class with something that does fancy interception. Perhaps in the parse/processing step of the `Legacy` component, these divs could be re-written to be the appropriate Component type.

IE:
```
<div data-id="welcome" data-view="Text" data-title="Hello" data-text="This is your shiny new dashboard." data-moreinfo="Protip: You can drag the widgets around!"></div>

becomes:

<Text data-id="welcome" data-title="Hello" data-text="This is your shiny new dashboard." data-moreinfo="Protip: You can drag the widgets around!"></Text>
```

**Comment by tylermauthe** [comment]
Rather than performing the transpilation to React at runtime, it would probably be wise to do this at build time. Performant and easy-to-write React components need a build step anyway and webpack is the way to go, it might be possible to do this with a webpack plugin! We will still need an adapter for the transpiled components to extend, but I can actually imagine this being possible. I was pretty skeptical that any of my above suggestions could be done in a performant way.

This plugin could be used to completely convert a component to the new React way of doing things too. I'll explore the possibility of doing this also.

**Comment by tylermauthe** [comment]
Gosh I hope I have free time again one day to work on this... Life moves so fast sometimes.

**Comment by tylermauthe** [comment]
So, I've been thinking about this a lot. I am convinced it's possible; but I just don't think I'll ever have time to really implement it. Maybe around Christmas time if I need a vacation from my vacation...

We can easily work around this problem by including the legacy `dashing.coffee` source in some conditional fashion, so I'm not sure it's worth the effort of implementing this adaptor. That being said, I think it's a really interesting problem... But it'll take a week or two of full-time effort to pull this off.

Unless I find myself with two weeks of free time and nothing to do, I'm advocating for option 1 -- despite the sad implications of this decision.

**Comment by slm4996** [comment]
Just came across https://svelte.technology/blog/frameworks-without-the-framework/ , if a rewrite is in the works, why not make it as fast as possible? Also, mentioned in this article is inferno, which is react compatible, but insanely fast.

**Comment by tylermauthe** [comment]
@slm4996 - Svelte looks really cool, I love fast little frameworks like that. Riot.js is similarly small and fast. However, both are fairly obscure frameworks and the whole purpose of this exercise is to adopt a framework that is well-supported. I don't foresee Facebook or the React community dropping support any time soon.

One of the challenges I'm facing with this re-write, which is why I created this ticket, is that it's not a simple matter to migrate an ecosystem of developers to a new mode of doing things. A ton of Dashing dashboards were created by people with no front-end experience and very little Ruby experience. On the other end, some use cases have hundreds of dashboards being shown on hundreds of TVs at various offices of large enterprises - presumably this case has much more sophisticated development support. In either case, moving that ship is difficult - the first from a skills perspective and the second from a cost-benefit perspective. The key design goal behind any development in Smashing will be to support and foster a stable and reliable architecture that will create spaces for teams to be creative and provide value within the constraints of their use case while supporting their future needs.

That being said, Inferno seems awesome. It looks like it's almost fully compatible with React, but there are rough edges:
https://github.com/infernojs/inferno/tree/master/packages/inferno-compat#what-is-missing

I'm not sold on the idea of using a drop-in replacement that isn't fully compatible, it's just going to open up future incompatibility risks! Thanks for your input and I fully agree with the desire to have an insanely fast rewrite -- compared to Batman, React will be like a rocket ship.

**Comment by tylermauthe** [comment]
Writing the above has inspired me to take another stab at this issue!

**Comment by MartynKeigher** [comment]
Yay!!!! :)

**Comment by tylermauthe** [comment]
Just chatting with @spiramira and I just don't think this is reasonable or feasible. I've hit a wall of analysis paralysis around this.

I'm just going to suck it up and migrate. I'll create an upgrade guide, post it to the wiki, and take requests for widget migrations.
