### ISSUE TITLE
Whats the correct way the access last data from a widget?

### ISSUE THREAD

**Issue by gipsh** [Smashing/smashing#100]
I want to update a widget based on the data i sent the last time. 
Should i parse the history.yml file ? 
I see a method on the api called `latest_events` but it returns all the raw events. 

Could be nice to have a method called `get_data({widget_id})`  which returns the current data.

**Comment by gipsh** [comment]
Finally i used the api with `settings.history` to access my widget data.

**Comment by tylermauthe** [comment]
Inside a job, I would store the state in a variable outside the scope of the `SCHEDULER` block. In a widget, I would make a property on the widget to store the last value. If I wanted more history, I would use arrays instead of values.
