### ISSUE TITLE
Stale links to BatmanJS

### ISSUE THREAD

**Issue by RonanC** [Smashing/smashing#111]
On the home-page there are multiple dead links to the BatmanJS project:
https://smashing.github.io/

Should we remove these, or can we update the links?

**Comment by tylermauthe** [comment]
Yes please! We happily accept PRs!

**Comment by kinow** [comment]
I believe this was fixed after we updated the web site. Couldn't find any links on https://smashing.github.io, nor on the Wiki (looked at the first links at the top of the ToC).
