### ISSUE TITLE
Installation guide is not related to smashing?

### ISSUE THREAD

**Issue by KuenzelIT** [Smashing/smashing#115]
Hi,

I just had a little problem installing smashing on Linux Mint and I found the solution in the following old issue:
https://github.com/Smashing/smashing/issues/28

There @kinow said he wanted to update the installation guide for Ubuntu with the following line 
```
apt install build-essential
```

Thats when I checked the Installation guide in the wiki which is not related to smashing but Ruby(?).

Is that guide old / am I at the wrong place?

Thanks to @kinow my installation now succeeded.

**Comment by kinow** [comment]
Hi @KuenzelIT !

Glad it helped, and thanks for pointing the old ticket. I never updated the documentation, sorry.

I can't find a good place to add this information in the Wiki. We also don't have anything specifically for Red Hat distros now (like ruby-devel, which from what I remember I also had issues with in some old rhel box).

So closing for now as invalid. We created a channel for questions and general discussions like this one (see https://github.com/Smashing/smashing/blob/master/CONTRIBUTING.md), just so it was easier to manage the issues here as we have few developers triaging issues.

Feel free to join the chat and suggest somewhere to put this info :-)
