### ISSUE TITLE
smashing.AnimatedValue throws error

### ISSUE THREAD

**Issue by mohsinali** [Smashing/smashing#117]
I tried using `@accessor 'value', smashing.AnimatedValue`, but this throws error that smashing is not defined.

I changed it to `@accessor 'value', Dashing.AnimatedValue` and it worked. Can anyone verify if this is a valid change.

**Comment by kinow** [comment]
I believe this is a [valid change](https://github.com/Smashing/smashing/blob/4d5e6450cada54356f4713c08ec2ef015c405604/javascripts/dashing.coffee#L91), and thanks for updating the Wiki too.
