### ISSUE TITLE
How to Get Current URL and URI  In Smashing

### ISSUE THREAD

**Issue by manikandanselva** [Smashing/smashing#125]
Hi 
I Try to get current url in ruby

puts request.original_url

bt i get following error : Request is a not a local variable

**Comment by gregology** [comment]
what about url?
```
[2] pry(#<Sinatra::Application>)> request.url
=> "http://localhost:3030/sample"
```

**Comment by kinow** [comment]
For questions, feel free to contact us directly on the [gitter chat](https://gitter.im/Smashing/Lobby) @manikandanselva
