### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by JeroenV99** [Smashing/smashing#126]
maby a idea for a widget that can play spotify and show a now playing

**Comment by kinow** [comment]
Hi @JeroenV99 , if you create the widget, we can add it to [the list of additional widgets](https://github.com/Smashing/smashing/wiki/Additional-Widgets).

In this repository, we maintain only the default bundled widgets :+1: (but good idea, would be cool to see some playlist in a dashboard).

Cheers
Bruno
