### ISSUE TITLE
 no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by Lavrih** [Smashing/smashing#131]
Hi 
I am trying to learn smashing and i got a bunch of errors. I solved them all, but now i don't know how to solve this one.

Thanks 
![Screenshot_1](https://user-images.githubusercontent.com/39552769/56205600-8e22c300-604a-11e9-8f96-3fb112a62ab3.png)

**Comment by DismissedGuy** [comment]
I had the same problem today. It seems to be related to this issue: https://github.com/oneclick/rubyinstaller2/issues/96
Executing `gem uninstall eventmachine` followed by `gem install eventmachine --platform ruby` seems to fix it.

**Comment by kinow** [comment]
@Lavrih, see comment above from @DismissedGuy (thanks!). If you have further questions check out the gitter chat (link in the readme file)
