### ISSUE TITLE
which file or which place add curl code?

### ISSUE THREAD

**Issue by manikandanselva** [Smashing/smashing#136]
which file or which place add  code?

https://gist.github.com/hussfelt/a6fe71ebd7cce327df29

Curl -d '{
"auth_token": "YOUR_AUTH_TOKEN",
"src": "http://example.com/"
}' http://0.0.0.0:3030/widgets/iframeId1

**Comment by atilleh** [comment]
Could you please add more information about the issue encountered ? What do you mean ?
Please follow the guide provided in your link : https://gist.github.com/hussfelt/a6fe71ebd7cce327df29.

The curl command is used to update the cell.

**Comment by kinow** [comment]
Feel free to drop a message to our [gitter channel](https://gitter.im/Smashing/Lobby) if you have other questions @manikandanselva
