### ISSUE TITLE
Fix Travis build on master

### ISSUE THREAD

**Issue by kinow** [Smashing/smashing#138]
Found while reviewing #137 that the master branch is currently broken.

It should be some dependency, or maybe something in Travis. So whoever finds time to have a look and fix it, it'd be much appreciated (currently overseas with limited bandwidth, but will investigate it otherwise when I return home)

**Comment by YtvwlD** [comment]
This just applies to Ruby versions 2.2 and 2.3. They aren't being supported, anymore.

Perhaps we should just remove them from the CI matrix and add 2.5 and 2.6 instead?

**Comment by kinow** [comment]
>Perhaps we should just remove them from the CI matrix and add 2.5 and 2.6 instead?

Could be. Let's wait for others to chime in. Might drop a note to gitter later if there's no response here.
