### ISSUE TITLE
Can't have a dashboard with a number in its name?

### ISSUE THREAD

**Issue by brandonsturgeon** [Smashing/smashing#139]
Using Smashing with Nginx on Ubuntu 16.04 LTS

When my homepage is named `test.erb` it works just fine when visiting `/test`, but when it's called `test3.erb` I get smashing's 404 page when visiting `/test3`

**Comment by kinow** [comment]
Might be something with your nginx config. Just tried it and it worked for me. Can you try accessing it directly without nginx?

**Comment by brandonsturgeon** [comment]
Huh, seems you're right. I thought I had tried everything on nginx's side. Thanks! I'll close this and update with my findings for anyone else who stumbles across this later.
