### ISSUE TITLE
Demo and screenshots

### ISSUE THREAD

**Issue by dmikester1** [Smashing/smashing#142]
Can we get a demo and screenshots added to the main Github page?  I want to see what this looks like.

**Comment by kinow** [comment]
Hi @dmikester1 

We have one screenshot in the main page (https://smashing.github.io/), near the bottom. But perhaps a section in the Documentation (which points to this repository's Wiki) called "Screenshots" could be useful to new users.

We used to have a demo hosted on Heroku, but maintaining that would also require someone to keep an eye on its status and kicking it should it goes down. Perhaps we could use just a Screenshots section, with static images, and also with GIF's/screencasts.

This is a good first issue. So if you are interested in this and have some spare time, pull requests and Wiki edits are welcome :)

Cheers
Bruno
