### ISSUE TITLE
Anyone knows where I can find Batman.js documentation?

### ISSUE THREAD

**Issue by CaveDweller92** [Smashing/smashing#144]
I'm new to Smashing / Dashing.io. So far on what I read what I understood was to create a custom widget you need to know Batman.js. Since Batman.js git repo is no longer exists how can I learn Batman.js?

**Comment by lewis-fidlers** [comment]
[Web archive](https://web.archive.org/web/20171108081138/http://batmanjs.org/docs/index.html) Still has docs though not ideal it could be a good way to start :)

**Comment by kinow** [comment]
Thanks @lewis-fidlers , sorry @CaveDweller92 not aware of where to find it, you may want to search the web archive, or try to find a (former?) maintainer/developer or community. Feel free to chat in our gitter room if you have other questions similar to this one. We try to use issues in this repository only for feature/bug requests :+1:

**Comment by CaveDweller92** [comment]
Thanks. will do.

**Comment by lewis-fidlers** [comment]
For future reference.

I've reached out to Daniel who initially started dashing and he was kind enough to get the batmanjs documentation up again. 

from his email:
```
It's back up now at http://batmanjs.org/. This version doesn't have the deprecation notice on it, but we're going to add it back in there showing that it's no longer actively maintained. Hope this helps!
```
