### ISSUE TITLE
Sample page dashboard not load on Windows 10/Chrome 83.0.4103.116

### ISSUE THREAD

**Issue by bhupeshdahal** [Smashing/smashing#172]
**Describe the bug**
After installation out of the box sample dashboards does not load

**To Reproduce**
1.  Install Smashing 
2. Start Server >> Error with Event Machine (had to uninstall and re-install this)
3. Start  server again

**Expected behavior**
Localhost:3030 does not load dashboard

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/5194503/91903423-3aca0880-ec71-11ea-97f0-7bea6e60a860.png)
![image](https://user-images.githubusercontent.com/5194503/91903577-706ef180-ec71-11ea-9f2e-913e1ec10beb.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome 83.0.4103.116

**Comment by kinow** [comment]
Anything in the browser console?

**Comment by bhupeshdahal** [comment]
https://github.com/Shopify/dashing/issues/249  seems like samte issue; It got resolved after installing nodejs on my machine

**Comment by kinow** [comment]
Probably missing `npm` or coffe script. I found it while writing the docs for Windows: https://github.com/Smashing/smashing/wiki/Installation#sample-dashboard-does-not-load-on-windows-shows-only-a-blank-screen (might be worth checking `npm` is available even if on Linux).

Feel free to re-open if you have confirmed the issue persists even after install npm/node (worth trying installing coffeescript too perhaps).

Thanks!
Bruno
