### ISSUE TITLE
smashing fails to install on macOS with built-in ruby (2.6)

### ISSUE THREAD

**Issue by qthatswho** [Smashing/smashing#175]
**Describe the bug**
Smashing fails to install using the built-in version of Ruby included with macOS.

**To Reproduce**
1. run `gem install smashing` on macOS Catalina or Big Sur

**Expected behavior**
Successful installation of Smashing

**Actual behavior**
$ gem install smashing
Fetching execjs-2.7.0.gem
Fetching coffee-script-source-1.12.2.gem
Fetching coffee-script-2.4.1.gem
Fetching rack-2.2.3.gem
Fetching tilt-2.0.10.gem
Fetching rack-protection-2.0.8.1.gem
Fetching ruby2_keywords-0.0.2.gem
Fetching mustermann-1.1.1.gem
Fetching sinatra-2.0.8.1.gem
Fetching backports-3.20.1.gem
Fetching multi_json-1.15.0.gem
Fetching sinatra-contrib-2.0.8.1.gem
Fetching daemons-1.3.1.gem
Fetching eventmachine-1.2.7.gem
Fetching thin-1.7.2.gem
Fetching raabro-1.4.0.gem
Fetching concurrent-ruby-1.1.7.gem
Fetching tzinfo-2.0.4.gem
Fetching et-orbi-1.2.4.gem
Fetching fugit-1.4.1.gem
Fetching rufus-scheduler-3.6.0.gem
Fetching thor-1.0.1.gem
Fetching sprockets-4.0.2.gem
Fetching ffi-1.14.2.gem
Fetching smashing-1.3.0.gem
Fetching sassc-2.4.0.gem
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur (also occurs on Catalina)
 - ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]

Notes:

I also tried a variety of workarounds including trying rvm, installing various Ruby versions with Hombrew, all resulting in a variety of subsequent failures. What I'd like to see as a resolution to this bug report is a clear, verified set of instructions for installing on macOS posted to the Wiki. Thanks!

**Comment by JCluzet** [comment]
hi, just run with sudo and -n /local/usr/bin option

**Comment by kinow** [comment]
Thanks @JCluzet !

@qthatswho , I believe @JCluzet is right, and using `sudo`, or rbenv (as long as its destination folder is writable) should fix your problem.

>What I'd like to see as a resolution to this bug report is a clear, verified set of instructions for installing on macOS posted to the Wiki. Thanks!

Fair point :-) I've added the section to the Wiki, and will add an issue (just search to see if we have one already). Feel free to contribute to that Wiki page if you have time. I have the latest Ubuntu to test, and also a Win10 pro box, but no macos, so it will depend on volunteers to help with that task.

https://github.com/Smashing/smashing/wiki/Installation#macos

Thanks!
