### ISSUE TITLE
Smashing not displaying data

### ISSUE THREAD

**Issue by gazzmanzx6** [Smashing/smashing#180]
**Describe the bug**
After updating Smashing to 1.3.2 from 1.2.0 my dashboard no longer receives values from the netatmo and klimato widgets.
The widgets show in the dashboard but without any data.

**To Reproduce**
1. Update Smashing to 1.3.2

**Expected behavior**
Display data from netatmo and klimato widgets.

**Screenshots**
 - Smashing 1.2.0
![Screenshot 2021-02-28 at 3 10 11 pm](https://user-images.githubusercontent.com/44817821/109423397-17d9a080-79d7-11eb-9288-5eea16680693.jpg)
 - Smashing 1.3.2
![Screenshot 2021-02-28 at 3 16 08 pm](https://user-images.githubusercontent.com/44817821/109423581-e90ffa00-79d7-11eb-8e3f-c54a4ef1004c.jpg)

**Desktop:**
 - OS: Raspbian Buster
 - Browser Chromium
 - Ruby and gems versions
ruby 2.5.7p157 (2019-03-15 revision 67260) [arm-linux-gnueabihf]
backports (3.18.2, 3.17.0)
bigdecimal (default: 1.3.4)
bundler (2.2.11, 2.1.4)
cmath (default: 1.0.0)
coffee-script (2.4.1)
coffee-script-source (1.12.2)
concurrent-ruby (1.1.8, 1.1.7, 1.1.6)
csv (default: 1.0.0)
curb (0.9.11, 0.9.10)
daemons (1.3.1)
date (default: 1.0.0)
dbm (default: 1.0.0)
did_you_mean (1.2.1)
et-orbi (1.2.4)
etc (default: 1.0.0)
eventmachine (1.2.7)
execjs (2.7.0)
fcntl (default: 1.0.0)
ffi (1.14.2, 1.13.1)
fiddle (default: 1.0.0)
fileutils (default: 1.0.2)
fugit (1.4.2, 1.3.8)
gdbm (default: 2.0.0)
io-console (default: 0.4.6)
ipaddr (default: 1.2.0)
json (2.5.1, 2.3.1, 2.3.0, default: 2.1.0)
minitest (5.11.3)
multi_json (1.15.0, 1.14.1)
mustermann (1.1.1)
net-telnet (0.1.1)
openssl (default: 2.1.2)
power_assert (1.1.1)
psych (default: 3.0.2)
raabro (1.4.0, 1.3.1)
rack (2.2.3, 2.0.9)
rack-protection (2.1.0, 2.0.8.1)
rake (12.3.1)
rdoc (default: 6.0.1)
ruby2_keywords (0.0.4, 0.0.2)
rufus-scheduler (3.7.0, 3.6.0, 3.4.2)
sass (3.4.25)
sassc (2.4.0)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
sinatra (2.1.0, 2.0.8.1)
sinatra-contrib (2.1.0, 2.0.8.1)
smashing (1.3.2)
sprockets (4.0.2, 3.7.2)
stringio (default: 0.0.1)
strscan (default: 1.0.0)
test-unit (3.2.8)
thin (1.8.0, 1.7.2)
thor (1.1.0, 1.0.1, 0.19.4)
tilt (2.0.10)
tzinfo (2.0.4, 2.0.2, 2.0.1)
webrick (default: 1.4.2)
xmlrpc (0.3.0)
zlib (default: 1.0.0)
 
**Notes:**
Uninstalling 1.3.2 and reinstalling 1.2.0 gets it working again.

**Comment by kinow** [comment]
@gazzmanzx6 are you able to share a little more about your dashboard? If not the source code, then perhaps just confirm that you have ID's for each widget used in your dashboard?

**Comment by toy** [comment]
Tried to find widgets, are those https://github.com/olf/dashing_netatmo and https://github.com/danillotuhumury/klimato-dashing-widget?

**Comment by kinow** [comment]
I found the same repo for the netatmo widget.

**Comment by gazzmanzx6** [comment]
The weather widget is [https://github.com/alexanderbecher/klimato-dashing-widget](url)
The netatmo widget is the one you have linked to.
@kinow I'm not sure what you mean by ID's for each widget?

**Comment by kinow** [comment]
Thanks @gazzmanzx6 . Would you be able to share an example dashboard to reproduce the issue?

**Comment by gazzmanzx6** [comment]
[dashboard.zip](https://github.com/Smashing/smashing/files/6063316/dashboard.zip)
This is my dashboard.

**Comment by kinow** [comment]
I think the job for klimato is not sending an event with ID `wunderground`. Still not sure why :confused:

**Comment by gazzmanzx6** [comment]
I didn't think it used wunderground but yahoo weather?

**Comment by kinow** [comment]
@gazzmanzx6 I think I got it working.

![image](https://user-images.githubusercontent.com/304786/109569343-2cd84000-7b4d-11eb-962e-5388bb07d66f.png)

To confirm I'm using the latest version, I checked the browser network tab for the `/events` subscription, and confirmed it's using the `ids` parameter.

![image](https://user-images.githubusercontent.com/304786/109569413-4a0d0e80-7b4d-11eb-89d4-e1cc2ad3f8bd.png)

In `desktop.erb`, the `data-view` of the WUnderground widget was wrong.

```html
<!-- was -->
        <li data-row="2" data-col="1" data-sizex="1" data-sizey="1">
            <div class="background-secondary-2-0" data-id="wunderground" data-view="Wunderground" data-title="WUnderground" data-postfix=""></div>
        </li>


<!-- fixed with -->

        <li data-row="2" data-col="1" data-sizex="1" data-sizey="1">
            <div class="background-secondary-2-0" data-id="wunderground" data-view="Klimato" data-title="WUnderground" data-postfix=""></div>
        </li>
```

And then the job `klimato.rb` I added my API key and details, and also:

```ruby
# was

    send_event "klimato", { location: location["city"], temperature: today["temperature"], code: today["code"], format: format,
    forecast1: forecast[1]["low"].to_s+"\u00b0 - "+forecast[1]["high"].to_s+"\u00b0", forecast1Icon: forecast[1]["code"], forecast1day: forecast[1]["day"].upcase,
    forecast2: forecast[2]["low"].to_s+"\u00b0 - "+forecast[2]["high"].to_s+"\u00b0", forecast2Icon: forecast[2]["code"], forecast2day: forecast[2]["day"].upcase}

# fixed with

    send_event "wunderground", { location: location["city"], temperature: today["temperature"], code: today["code"], format: format,
    forecast1: forecast[1]["low"].to_s+"\u00b0 - "+forecast[1]["high"].to_s+"\u00b0", forecast1Icon: forecast[1]["code"], forecast1day: forecast[1]["day"].upcase,
    forecast2: forecast[2]["low"].to_s+"\u00b0 - "+forecast[2]["high"].to_s+"\u00b0", forecast2Icon: forecast[2]["code"], forecast2day: forecast[2]["day"].upcase}
```

This way Smashing is able to automatically subscribe the widgets to the events, and load the widgets/views.

**Comment by kinow** [comment]
> I didn't think it used wunderground but yahoo weather?

It's using Yahoo Weather. I created a test app/API Key.

![image](https://user-images.githubusercontent.com/304786/109569849-f7802200-7b4d-11eb-9b72-2927be1ec5ce.png)

But in your dashboard the `data-id` and `data-title` have WUnderground. The Widget used is Klimato. And the data from Yahoo Weather (which is closing in a few days/months I think, BTW).

**Comment by gazzmanzx6** [comment]
The only dashboards I use are the ones named raspi.erb & raspi2.erb.
Are you saying that the fact it is wrong in an unused desktop is causing the problem?
If so, I presume I can just delete the desktop.erb file and it should all work again?

**Comment by kinow** [comment]
> The only dashboards I use are the ones named raspi.erb & raspi2.erb.
> Are you saying that the fact it is wrong in an unused desktop is causing the problem?

No, sorry. I just tried the first dashboard that was loaded when I started smashing with your archive. I hadn't seen other dashboards.

> If so, I presume I can just delete the desktop.erb file and it should all work again?

I don't think so, just tried that to confirm and it didn't fix the issue. For some reason after I start your `raspi` dashboard, the `/events?ids=` URL did not include the Widgets' IDs. Let me see why not…

![image](https://user-images.githubusercontent.com/304786/110188583-20235700-7e81-11eb-8162-12b9c110bfaf.png)

**Comment by kinow** [comment]
Ah! Tested with @toy 's #182 PR, and now the dashboard data was loaded successfully. Let me see if we can merge that PR and release a new version :+1: 

![image](https://user-images.githubusercontent.com/304786/110189229-49dd7d80-7e83-11eb-8418-6bbc39bb1f15.png)

**Comment by kinow** [comment]
@gazzmanzx6 let's try again :-)

Released with 3.3.0, could you try that latest version and see if that works for you, please? Should be in RubyGems in ~20 minutes or less.

**Comment by gazzmanzx6** [comment]
@kinow just updated to latest version and all is working again.

Thanks for your quick efforts on this.

**Comment by kinow** [comment]
Thank you for your patience and for confirming it's working now. Kudos to @toy for fixing it so quickly :tada:
