### ISSUE TITLE
Smashing 1.3.2 still not showing data

### ISSUE THREAD

**Issue by gazzmanzx6** [Smashing/smashing#183]
In reference to #180, which was closed without a fix, I can confirm this is still not working for me.
I have removed any references to Wunderground but the data for the other widgets is not loading.
Reverting back to version 1.2.0 fixes this problem.

*** LOCAL GEMS ***

backports (3.20.2, 3.18.2, 3.17.0)
bigdecimal (3.0.0, default: 1.3.4)
bundler (2.2.13, 2.2.11, 2.1.4)
cmath (default: 1.0.0)
coffee-script (2.4.1)
coffee-script-source (1.12.2)
concurrent-ruby (1.1.8, 1.1.7, 1.1.6)
csv (3.1.9, default: 1.0.0)
curb (0.9.11)
daemons (1.3.1)
date (3.1.1, default: 1.0.0)
dbm (default: 1.0.0)
did_you_mean (1.5.0, 1.2.1)
et-orbi (1.2.4)
etc (1.2.0, default: 1.0.0)
eventmachine (1.2.7)
execjs (2.7.0)
fcntl (default: 1.0.0)
ffi (1.14.2)
fiddle (default: 1.0.0)
fileutils (1.5.0, default: 1.0.2)
fugit (1.4.2)
gdbm (default: 2.0.0)
io-console (0.5.8, default: 0.4.6)
ipaddr (1.2.2, default: 1.2.0)
json (2.5.1, default: 2.1.0)
minitest (5.14.4, 5.11.3)
multi_json (1.15.0)
mustermann (1.1.1)
net-telnet (0.2.0, 0.1.1)
openssl (default: 2.1.2)
power_assert (2.0.0, 1.1.1)
psych (3.3.1, default: 3.0.2)
raabro (1.4.0)
rack (2.2.3, 2.0.9)
rack-protection (2.1.0, 2.0.8.1)
rake (13.0.3, 12.3.1)
rb-fsevent (0.10.4)
rb-inotify (0.10.1)
rdoc (6.3.0, default: 6.0.1)
ruby2_keywords (0.0.4, 0.0.2)
rufus-scheduler (3.7.0, 3.6.0, 3.4.2)
sass (3.7.4, 3.4.25)
sass-listen (4.0.0)
sassc (2.4.0)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
sinatra (2.1.0, 2.0.8.1)
sinatra-contrib (2.1.0, 2.0.8.1)
smashing (1.2.0)
sprockets (4.0.2, 3.7.2)
stringio (3.0.0, default: 0.0.1)
strscan (3.0.0, default: 1.0.0)
test-unit (3.4.0, 3.2.8)
thin (1.8.0, 1.7.2)
thor (1.1.0, 1.0.1, 0.19.4)
tilt (2.0.10)
tzinfo (2.0.4)
webrick (1.7.0, default: 1.4.2)
xmlrpc (0.3.2, 0.3.0)
zlib (1.1.0, default: 1.0.0)
[dashboard.zip](https://github.com/Smashing/smashing/files/6091083/dashboard.zip)

**Comment by kinow** [comment]
Hi @gazzmanzx6 

Sorry for not updating the other issue. Even though it's closed, it has the issue context and could be re-opened. We can use this or that issue, whichever you prefer. I was planning to, but then we had a report #181 and I got sidetracked.

It's already weekend here in NZ, and I might have time to continue working on 1.3.2 issues today or tomorrow :+1: :crossed_fingers: 

Cheers
Bruno

**Comment by gazzmanzx6** [comment]
Reopening the original would be best I think.
Thanks.
