### ISSUE TITLE
Example dashboard don't show widgets

### ISSUE THREAD

**Issue by JCluzet** [Smashing/smashing#195]
Hi, 
I have installed smashing with basic command, but when I launch the localhost:3030 I don't see any widgets, only the sequence` Try this`: 

![Screenshot 2022-10-26 at 00 21 31](https://user-images.githubusercontent.com/55356071/197893130-b56355ec-d480-43fe-bed3-93ebfe1b5432.png)

![Screenshot 2022-10-26 at 00 22 14](https://user-images.githubusercontent.com/55356071/197893237-2f0a2ae0-151f-44dc-9ea9-8d2387436a38.png)

Thank you!

**Comment by kinow** [comment]
Anything in the browser JS console?

**Comment by JCluzet** [comment]
Hi 👋
Thank you very much for helping me

Yes I see this error in JS console : 
![Screenshot 2022-10-26 at 01 52 08](https://user-images.githubusercontent.com/55356071/197903194-dc2cf6a7-3f24-4f71-ac72-de24594b6245.png)

Also I have only 2 extensions that have nothing to do with Javascript.
I have just tried to deactivate them but it doesn't change anything.

**Comment by kinow** [comment]
Thanks for the screenshots. I remember users reporting issues due to the version (or missing) of NPM. Could you share your versions of npm, ruby, and smashing (I believe you have the latest?), please?

Thanks!
Bruno

**Comment by JCluzet** [comment]
Whaw thanks you !
I found the answer!
When doing `npm -v,` nothing was displayed, my version of npm must have been corrupted.
I reinstalled npm by following this tutorial: https://askubuntu.com/questions/1036806/how-to-remove-npm-and-reinstall-npm-completely-in-18-04

And now the widgets are displayed again!
Thanks for your help and congratulations for this great project!

**Comment by kinow** [comment]
Not a problem. Thanks for letting us know it worked! 🙌
