### ISSUE TITLE
Ubuntu 16 installation failure.

### ISSUE THREAD

**Issue by Guyverix** [Smashing/smashing#28]
Still learning the basics for dealing with Ruby.  _This might not be an application issue, but an ignorance issue._  
I cannot install per your install instructions due to errors on "(sudo) gem install smashing"
The error in the logs states:
package configuration for openssl is not found
openssl is the latest version, and I installed libssl-dev as well from searching google.

Is this  an issue, or am I missing something basic?
Fresh install of Ubuntu 16, completely up to date on all packages.

**Comment by kinow** [comment]
Hi @Guyverix 

I'm on Ubuntu 16.04.1 LTS, and that works for me. So more likely we have some different dependencies :-) very likely something with Ruby.

Can you try the following?

```
kinow@linux:~$ irb
irb(main):001:0> require 'openssl'
=> true
irb(main):002:0>
```

**Comment by Guyverix** [comment]
Looks like that is successful for me:
$ irb
irb(main):001:0> require 'openssl'
=> true
irb(main):002:0>

**Comment by kinow** [comment]
Nice. I wonder if this list of packages installed in my notebook containing ssl might help?

```
root@linux:/home/kinow# dpkg -l | grep ssl
ii  libflac8:amd64                                                        1.3.1-4                                       amd64        Free Lossless Audio Codec - runtime C library
ii  libflac8:i386                                                         1.3.1-4                                       i386         Free Lossless Audio Codec - runtime C library
ii  libgnutls-openssl27:amd64                                             3.4.10-4ubuntu1.1                             amd64        GNU TLS library - OpenSSL wrapper
ii  libio-socket-ssl-perl                                                 2.024-1                                       all          Perl module implementing object oriented interface to SSL sockets
ii  libnet-smtp-ssl-perl                                                  1.03-1                                        all          Perl module providing SSL support to Net::SMTP
ii  libnet-ssleay-perl                                                    1.72-1build1                                  amd64        Perl module for Secure Sockets Layer (SSL)
ii  libssl-dev:amd64                                                      1.0.2g-1ubuntu4.5                             amd64        Secure Sockets Layer toolkit - development files
ii  libssl-doc                                                            1.0.2g-1ubuntu4.5                             all          Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.0:amd64                                                     1.0.2g-1ubuntu4.5                             amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.0.0:i386                                                      1.0.2g-1ubuntu4.5                             i386         Secure Sockets Layer toolkit - shared libraries
ii  libwavpack1:amd64                                                     4.75.2-2                                      amd64        audio codec (lossy and lossless) - library
ii  openssl                                                               1.0.2g-1ubuntu4.5                             amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  ssl-cert                                                              1.0.37                                        all          simple debconf wrapper for OpenSSL
```

Also, might be worth uninstalling smashing/dashing/eventmachine, and reinstalling it? Or running a `gem update`.

**Comment by Guyverix** [comment]
Hmm, I notice you specifically have a 32 bit installation of libssl installed as well.  Wonder if that could be the issue.  When I get back in the office in the morning I will install a 32 bit version, and give it a shot.  

I did run a gem update, and it appears to have updated most things, but errors on a few of the updates.

 dpkg -l | grep ssl
ii  libgnutls-openssl27:amd64          3.4.10-4ubuntu1.1                  amd64        GNU TLS library - OpenSSL wrapper
ii  libssl-dev:amd64                   1.0.2g-1ubuntu4.5                  amd64        Secure Sockets Layer toolkit - development files
ii  libssl-doc                         1.0.2g-1ubuntu4.5                  all          Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.0:amd64                  1.0.2g-1ubuntu4.5                  amd64        Secure Sockets Layer toolkit - shared libraries
ii  openssl                            1.0.2g-1ubuntu4.5                  amd64        Secure Sockets Layer toolkit - cryptographic utility

**Comment by Guyverix** [comment]
Installed all the SSL stuff to mirror your configuration:
<pre>
dpkg -l | grep ssl
ii  libgnutls-openssl27:amd64          3.4.10-4ubuntu1.1                  amd64        GNU TLS library - OpenSSL wrapper
ii  libio-socket-ssl-perl              2.024-1                            all          Perl module implementing object oriented interface to SSL sockets
ii  libnet-smtp-ssl-perl               1.03-1                             all          Perl module providing SSL support to Net::SMTP
ii  libnet-ssleay-perl                 1.72-1build1                       amd64        Perl module for Secure Sockets Layer (SSL)
ii  libssl-dev:amd64                   1.0.2g-1ubuntu4.5                  amd64        Secure Sockets Layer toolkit - development files
ii  libssl-doc                         1.0.2g-1ubuntu4.5                  all          Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.0:amd64                  1.0.2g-1ubuntu4.5                  amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.0.0:i386                   1.0.2g-1ubuntu4.5                  i386         Secure Sockets Layer toolkit - shared libraries
ii  openssl                            1.0.2g-1ubuntu4.5                  amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  ssl-cert                           1.0.37                             all          simple debconf wrapper for OpenSSL
</pre>
Still no luck.  I dont know if it makes a difference, but since I am new to working with Ruby I did NOT do anything other than an apt-get install ruby from the default repos.  There has been no additional configuration done.  

This is the log output that seems to be the source of my trouble..

<pre>
sudo gem install smashing
Building native extensions.  This could take a while...
ERROR:  Error installing smashing:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/eventmachine-1.2.1/ext
/usr/bin/ruby2.3 -r ./siteconf20161221-18713-70jmhx.rb extconf.rb
checking for main() in -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

---- SNIP ----

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/eventmachine-1.2.1/mkmf.log

---- SNIP ----

cat /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/eventmachine-1.2.1/mkmf.log
"gcc -o conftest -I/usr/include/x86_64-linux-gnu/ruby-2.3.0 -I/usr/include/ruby-2.3.0/ruby/backward -I/usr/include/ruby-2.3.0 -I. -Wdate-time -D_FORTIFY_SOURCE=2   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC conftest.c  -L. -L/usr/lib/x86_64-linux-gnu -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic     -lruby-2.3  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

package configuration for openssl is not found
</pre>

**Comment by kinow** [comment]
Well, think I found a way to reproduce, and **maybe** how to fix it.

Here's how I reproduced it:

```
cd /tmp
mkdir v1
cd v1
vagrant init ubuntu/xenial64
vagrant up
vagrant ssh
sudo su
apt update
apt install ruby ruby-dev openssl libssl-dev
gem install bundler
gem install smashing
```

Then got the same message as you have. And here's how I fixed it.

```
apt install build-essential
```

One of the transitive libraries installed must fix the issue. Let me know if that works for you @Guyverix and we can update the installation instructions with a block for Ubuntu users :+1:

**Comment by Guyverix** [comment]
Sorry for it taking so long to get back to you, the holidays are crazy.  That was it!  I was able to install properly once I installed the build-essential package.  

Thank you very much for figuring that out.  I was at a dead stop since I do not know Ruby all that well.  Now the real fun begins!

**Comment by indigca** [comment]
Kudos Kinow !
