### ISSUE TITLE
smashing start failing

### ISSUE THREAD

**Issue by JoshuaEdwards1991** [Smashing/smashing#29]
Hey! 

Thanks for taking the time to read this! 

I receive this error when running smashing start, following the quick start guide on the home page

smashing start
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
bundler: failed to load command: thin (/usr/local/bin/thin)
LoadError: cannot load such file -- rubyeventmachine
  /usr/local/share/gems/gems/eventmachine-1.2.1/lib/eventmachine.rb:8:in `require'
  /usr/local/share/gems/gems/eventmachine-1.2.1/lib/eventmachine.rb:8:in `<top (required)>'
  /usr/local/share/gems/gems/thin-1.6.4/lib/thin.rb:7:in `require'
  /usr/local/share/gems/gems/thin-1.6.4/lib/thin.rb:7:in `<top (required)>'
  /usr/local/share/gems/gems/thin-1.6.4/bin/thin:5:in `require'
  /usr/local/share/gems/gems/thin-1.6.4/bin/thin:5:in `<top (required)>'
  /usr/local/bin/thin:23:in `load'
  /usr/local/bin/thin:23:in `<top (required)>'

**Comment by phenomic01** [comment]
got the same error on my redhat maschine. installing nodejs (via yum) solved it for me.

**Comment by kinow** [comment]
Thanks @phenomic01 for chiming in! @JoshuaEdwards1991 can you try installing nodejs? Also take a look at #28 to see if anything in there might help you. Cheers

**Comment by JoshuaEdwards1991** [comment]
Hey guys! I have Nodejs installed through yum on my centos 7 vm. I can't understand why it falls over on the thin bit

**Comment by suhussai** [comment]
Which version of ruby are you using? 

I was able to replicate your issue on a Centos 7 container. I also tried installing nodejs and the issue persisted. I was running ruby version 2.0 so I thought I might try updating that. I used RVM to install ruby version 2.3 and used that to install and bundle the dependencies for smashing and when I ran `smashing start`, it worked.

```
[root@a4bee99a4f2d my-project]# cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)
```
```
[root@a4bee99a4f2d my-project]# ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
```
```
[root@a4bee99a4f2d my-project]# gem list

*** LOCAL GEMS ***

addressable (2.5.0)
backports (3.6.8)
bigdecimal (default: 1.2.8)
buftok (0.2.0)
bundler (1.13.7)
bundler-unload (1.0.2)
coffee-script (2.2.0)
coffee-script-source (1.12.2)
daemons (1.2.4)
did_you_mean (1.0.0)
domain_name (0.5.20161129)
equalizer (0.0.11)
eventmachine (1.2.1)
execjs (2.0.2)
executable-hooks (1.3.2)
faraday (0.10.0)
gem-wrappers (1.2.7)
hike (1.2.3)
http (2.1.0)
http-cookie (1.0.3)
http-form_data (1.0.1)
http_parser.rb (0.6.0)
io-console (default: 0.4.5)
json (default: 1.8.3)
memoizable (0.4.2)
minitest (5.8.5)
multi_json (1.12.1)
multipart-post (2.0.0)
naught (1.1.0)
net-telnet (0.1.1)
power_assert (0.2.6)
psych (default: 2.1.0)
public_suffix (2.0.4)
rack (1.5.5)
rack-protection (1.5.3)
rack-test (0.6.3)
rake (10.4.2)
rdoc (default: 4.2.1)
rubygems-bundler (1.4.4)
rufus-scheduler (2.0.24)
rvm (1.11.3.9)
sass (3.2.19)
simple_oauth (0.3.1)
sinatra (1.4.7)
sinatra-contrib (1.4.7)
smashing (1.0.0)
sprockets (2.10.2)
test-unit (3.1.5)
thin (1.6.4)
thor (0.19.4)
thread_safe (0.3.5)
tilt (1.4.1)
twitter (6.0.0)
tzinfo (1.2.2)
unf (0.1.4)
unf_ext (0.0.7.2)
```

**Comment by tylermauthe** [comment]
Hey Umair! Thanks for pitching in. Hope you had a nice break before heading back to school.

**Comment by tylermauthe** [comment]
Looks like @suhussai's suggestion should work, because RVM will install Ruby correctly along with the dependencies to build gems. I'm not sure why, but it appears EventMachine now has specific requirements for Ruby 2.2+ -- EventMachine is the library that thin uses to dispatch work to the Server-Sent Event socket.

Here's a more detailed breakdown if you're curious:
http://www.thinkplexx.com/learn/howto/linux/system/how-to-install-dashing-io-fixing-ruby-bundle-compile-and-other-issues

@JoshuaEdwards1991 - Please let us know if this works for you, thanks!

**Comment by tylermauthe** [comment]
Also, take a look at #6 please.

**Comment by tylermauthe** [comment]
Closing issue.

**Comment by JoshuaEdwards1991** [comment]
Thanks everyone, will give this a go today

**Comment by JoshuaEdwards1991** [comment]
Brilliant Ruby version 2.2.2 worked great thanks!

**Comment by monsdar** [comment]
Having the same issue on a Windows 10 machine. Never worked with Ruby before, so I freshly installed everything:
* Downloaded Ruby 2.4.2-2 64bit Windows Installer from the [official page](https://rubyinstaller.org/downloads/)
* After installation it starts a MSYS2 installer which I used to successfully install a compilation environment

I already have node.js installed (v6.9.1), but just used it for tinkering with npm.

I was following the main readme for creating a first project (gem install, smashing new, smashing start, ...)

I'll see if I can find something more, but as I'm totally new to Ruby any pointers that can help me are greatly appreciated

**Comment by monsdar** [comment]
Worked by compiling eventmachine myself following [this guide](https://stackoverflow.com/a/20950026/199513) from StackOverflow (nothing fancy needed, using the given commands worked out of the box)
