### ISSUE TITLE
Project Folder

### ISSUE THREAD

**Issue by MartynKeigher** [Smashing/smashing#32]
Hey all, 

Sorry if this has been asked before, but i cant seem to get my head around something,,,

I see that the projects are created by 'basically copying' what is in the `templates/project` folder (for the most part anyway!), yet, if i add stuff to that like a new widget, or updated javascript (that i want to apply/appear on each of my new projects) my new additions to the `templates/project` folder don't seem to appear in the new projects.

Why is that?; or better put...  What am I missing?

Thank you.

**Comment by tylermauthe** [comment]
Closing issue, discussed the solution with @MartynKeigher on gitter 👍
