### ISSUE TITLE
Investigate use of WebSockets

### ISSUE THREAD

**Issue by tylermauthe** [Smashing/smashing#34]
In the past, WebSockets were ignored in favour of SSEs. However, it seems that today WebSockets have better support in the Browser, Server and general Developer realms.

Specifically:

- IE11 and Edge would be a lot easier to make work with WebSockets (no SSE polyfill)
- Sinatra / Rack / Puma should [play together more nicely with WebSockets](http://stackoverflow.com/questions/13886426/sinatra-websocket-celluloid)
- The common perception is that WebSockets are cool and SSEs are crusty old who cares tech -- going with the flow on this is beneficial in terms of ecosystem popularity
- WebSockets may be easier to scale because:
  - They're more popular, so Load Balancers and other tools have been written with them in mind
  - Since it's a bi-directional link, the socket can be opened on page load and once the widgets are parsed the data subscriptions can be requested specifically for what's being rendered. With an SSE you are required to know what subscriptions you need before opening the socket

Given the above benefits, WebSockets should be investigated.

**Comment by pritesh-patel-hs** [comment]
Would you consider using a fallback library such as Socket.io or SockJs?

**Comment by tylermauthe** [comment]
@pritesh-patel-hs - That would be awesome, but I'm not sure about Ruby / Sinatra support for those. I've used Socket.io in Node before and SockJS with Java (Spring) -- both enjoyable experiences, though my preference would be Socket.io.

Out of curiosity, what's the use case for old browser support? WebSockets are pretty widely supported:
http://caniuse.com/#feat=websockets

More than SSE's:
http://caniuse.com/#search=eventsource

In any case, my main goal here is to hopefully kill two birds with one stone: Add support for modern versions of IE and Edge as well as make it easier to transition to Puma. The other points I mention are nice additional benefits.

If these goals can be met while ensuring fallback support, that is definitely the option I will favour.

I had to do some really nasty stuff involving two synchronized blocks and exceptions-as-flow-control to get Rack streaming working with Puma:
https://github.com/Smashing/smashing/compare/5c4460000a4098cb0d46263161b1eb7efc94c8e1...ee64d7df2d5850d723807ab36735f2a80ebe14a3#diff-ef95f95dc35a6b73d99a51e32d90ec48R82
https://github.com/Smashing/smashing/compare/5c4460000a4098cb0d46263161b1eb7efc94c8e1...ee64d7df2d5850d723807ab36735f2a80ebe14a3#diff-ef95f95dc35a6b73d99a51e32d90ec48R142

However, it looks like the same Puma issues will happen with WebSockets:
https://github.com/puma/puma/issues/895#issuecomment-241712400
https://github.com/sinatra/sinatra/pull/1114
https://github.com/sinatra/sinatra/issues/1035#issuecomment-204708957

Though there may be some fixes coming on these fronts soon. Rails 5 supports WebSockets and SSEs and Puma, so there's gotta be a way to make this work...

**Comment by pritesh-patel-hs** [comment]
The main reason is because I know a few people / companies using dashing on completely strip down Raspberry Pis using only the native browser epiphany and as far as I am aware it has only partial websocket support.

**Comment by blackness90** [comment]
@pritesh-patel-hs In company where I'am working we have it on Raspberry Pi and Chromium. It's working quite nice but the refresh time for bigger amount of widgets is noticable.

**Comment by stevenmaguire** [comment]
FYI - I was completely thrown off by the problems of hosting a smashing project on Heroku due to the SSE implementation. I added Pusher support to a fork of this project, and now it runs without issue on Heroku and completely skips the SSE pattern:

https://github.com/Smashing/smashing/compare/master...delivered:pusher-support

It is very specific to our needs and it could probably be updated to become a bit more productized, if someone were interested.

**Comment by rleir** [comment]
What do you think of jquery-graceful-websocket ? It looks like a good choice to me.
https://github.com/ffdead/jquery-graceful-websocket

**Comment by tylermauthe** [comment]
There’s no problems running dashing with SSE on heroku that I am aware of... What problems did you run into?

**Comment by tylermauthe** [comment]
@rleir I'd rather use Socket.io or SockJS - simply because there is more community adoption of them. The ruby gem cramp has support for socket.io on the server side - making the graceful fallback really simple to implement.

https://github.com/lifo/cramp/blob/master/examples/socketio/server.ru
