### ISSUE TITLE
Smashing JavaScript engine woes

### ISSUE THREAD

**Issue by tylermauthe** [Smashing/smashing#35]
Investigate whether use of `therubyracer` could eliminate the need for NodeJS as a dependency on Linux.

**Comment by boomshadow** [comment]
I added `therubyracer` to my bundle file instead of installing NodeJS. I've had no issues.

**Comment by kinow** [comment]
Never heard about it, but looks like it would simplify the whole build system. So +1 :-)

**Comment by tylermauthe** [comment]
I believe Ruby racer causes issues on Windows or macOS - but it's been ages since I looked closely at it. If anyone can easily test on those platforms it'd be much appreciated!

**Comment by kinow** [comment]
I have windows at work. Co-workers running mac, so I can try to test both. Is there a branch anywhere, or instructions what I'd need to change??
