### ISSUE TITLE
Smashing Debian Package

### ISSUE THREAD

**Issue by tylermauthe** [Smashing/smashing#39]
Make Smashing easy to install on Ubuntu.

**Comment by fredex2** [comment]
The package installation shall be a script or a package uploaded to the Debian/Ubuntu repository system (for automatic installation)?

**Comment by tylermauthe** [comment]
Good question! I don't know how this works exactly. I just want to make it really easy for people to install.

I suppose if we make a Debian package, we will have to find a place to host it. I don't know how that works, but I imagine it to be difficult. Anyone have any insights into this?

**Comment by tyler-mauthe-hs** [comment]
There's this:
https://github.com/krobertson/deb-s3

But then we'd have to pay for S3 hosting 😿 

I've worked with projects in CentOS where they provide a 'Source RPM' that allows you to build an RPM and install. I wonder if there's a Debian equivalent?

Or maybe we should just do as you suggested and build some sort of installation script...

**Comment by kinow** [comment]
I believe you can host it on launchpad for free, or you can ask for an official package in Ubuntu and Debian repositories (would have to ask someone like @rbrito about that)

**Comment by tylermauthe** [comment]
Looks promising! Thanks @kinow 

https://help.launchpad.net/Packaging/PPA

**Comment by webmaster128** [comment]
What is the advantage of having a Debian package over installation via ruby gems? I am a hardcore Ubuntu and It love the packaging system, but still I don't see how this is worth the effort. Isn't it better to concentrate on the installation method that works for all Linux distributions and OSX at the same time?

**Comment by tyler-mauthe-hs** [comment]
@webmaster128 Maybe this is a relic from Dashing, but we used to get a TON of support requests from poor sysadmin type folks who'd never used Ruby and had no idea how to install gems or why they were failing to install on <random distro>.

I'm thinking though that a docker container might increasingly be the better option.
