### ISSUE TITLE
Jenkins Smashing Dashboard

### ISSUE THREAD

**Issue by JoshuaEdwards1991** [Smashing/smashing#43]
Hey thanks for reading! 

I am looking to integrate smashing with data from jenkins.. has anyone done this before and have any advice on how this can be done?

Thnanks! 
Josh

**Comment by tylermauthe** [comment]
We have a list of additional widgets / jobs in the wiki: https://github.com/Smashing/smashing/wiki/Additional-Widgets

There are several Jenkins widgets and jobs there. However, when I made use of them I had to customize them slightly for my needs.

If you run into trouble with these implementation details, please direct your support requests to our Gitter chat room: https://gitter.im/Smashing/Lobby

GitHub issues should be reserved for bug reports and feature requests.
