### ISSUE TITLE
Simple tutorial for basic use

### ISSUE THREAD

**Issue by BabylonZeus** [Smashing/smashing#45]
After reading the site of dashing and smashing, it appears it is not simple to learn the tool for a basic need :
- I write a job erb which calls one authenticated API
- I extract some data
- I put it in the dashboard using a widget

After some time today on the tool, I still cannot manage to do this simple need, event with the help of the wiki.
A little tutorial for basics use cases would be nice.

Thanks!

**Comment by kinow** [comment]
Thanks for the feedback @BabylonZeus 

We can probably do better. And improving the documentation is always good, specially when it is based on user feedback.

Let us know if you have a draft or would like to submit pull requests or edit a Wiki page for that :-)

**Comment by rafiki270** [comment]
has there been anything created?
