### ISSUE TITLE
Dynamic OnClick URL on widgets

### ISSUE THREAD

**Issue by MichaelMadsen** [Smashing/smashing#46]
I've been searching around and so far haven't found a solution for this. My widget downloads and handles json with build data. I'd like to be able to click my widget and be taken to the current build url.

I've so far found several old issues from the dashing project, but they all seem to handle static URLs:
https://github.com/Shopify/dashing/issues/36

What I need is a way to open the dynamic url attribute from my job.rb when the widget is clicked.

Any help would be greatly appreciated, as I've been searching in vain for quite a while.

**Comment by MichaelMadsen** [comment]
I finally did it! Thanks to [this Stackoverflow answer](http://stackoverflow.com/questions/25869934/how-to-flip-switch-dashing-widget-on-click), I finally found a way of making my widget clickable with a dynamic url.

In the widget.rb job, when calling send_event, add a variable called 'link', containing the full url that should be opened on click.

in widget.coffee, add the following method:
```  
redirect: ->
  link = $(@node).find(".link")
  window.open(
    @link,
    '_blank'
  ); 
```
You can use the following if you want the current page to redirect, instead of op ening a new tab:
```
location.href = @link
```


And finally in the dashboard.erb file add the following to the widget definition:
```
data-event-click="redirect"
```

**Comment by QingsongYao** [comment]
@MichaelMadsen can you provide the full example of how to set link in html and where to put  data-event-click="redirect"?

**Comment by MichaelMadsen** [comment]
Let's modify the default text widget to be clickable.

The widget has 3 files - text.coffee text.html and text.scss found in the widgets->text folder.
You also have your .erb files in the dashboards folder, where you define your widgets.

I'm going to use the sampletv.erb file that's there by default. In this file, there is already a text box defined like this:
```
<li data-row="1" data-col="1" data-sizex="2" data-sizey="1">
      <div data-id="welcome" data-view="Text" data-title="Hello" data-text="This is your shiny new 1080p dashboard." data-moreinfo="Protip: You can drag the widgets around!"></div>
 </li>
```
We will add `data-event-click="redirect"`, so it looks like this:
```
<li data-row="1" data-col="1" data-sizex="2" data-sizey="1">
      <div data-id="welcome" data-view="Text" data-title="Hello" data-text="This is your shiny new 1080p dashboard." data-moreinfo="Protip: You can drag the widgets around!" data-event-click="redirect"></div>
 </li>
```

This tells the widget that you want the "redirect" method to be called when the widget is clicked.


Now let's go define the "redirect" method. Text.coffee is by default only one line. Modify it so it looks like this:
```
class Dashing.Text extends Dashing.Widget

  redirect: ->
    link = $(@node).find(".link")
    window.open(
      @link,
      '_blank'
    ); 
```
Or if you want to open the link in the same tab, do this instead:
```
class Dashing.Text extends Dashing.Widget

  redirect: ->
    link = $(@node).find(".link")
    location.href = @link
```
Note: it's very important that the entire redirect method is indented. So you need whitespace before the 'redirect' line. Copying the code directly from this post should work.

Now to make it dynamic, create a file called for instance updateTextLink.rb in the jobs folder. I've made a quick simple piece of code that updates the "welcome" widget every 5 seconds with a different url.
```

counter = 0
links = ["http://www.google.com/" , "http://www.bing.com/" , "http://www.github.com/Smashing/smashing/"]

SCHEDULER.every "5s", first_in: 0, timeout: "5s" do |prj|
  array_index = counter % 3
  link_to_send = links[array_index]
  send_event("welcome", {
          text: link_to_send,
          link: link_to_send
        })
  counter += 1
end
```

When you run your dashboard the text and link should change every 5 seconds.
I'm guessing that you already have a job.rb that handles your dynamic data, so you should just have to add the link property to your send_event method, and add the redirect method to your .coffee file.

Let me know if something is unclear or you need more information.

**Comment by QingsongYao** [comment]
Thank you MichaelMadsen. For my case, my job return a list of items. and each item has an url, and my .html file is 

<ul class="items list-nostyle">
  <li class="item" data-foreach-item="items" data-bind-class="item.widget_class">
    

    <span class="label repo" data-bind="item.repo" </span>
    <span class="label branch" data-bind="item.branch" </span>
    <span class="label branch" data-bind="item.status" </span>
    <div class="clearfix" />
  </li>
</ul>

I tried your method above, but it does not work.

**Comment by QingsongYao** [comment]
I found out the solution:  using <a data-bind-href="item.build_url"> to achieve this.

**Comment by boredwookie** [comment]
@QingsongYao I am in the same boat where I have a list of items that I would like to associate dynamic URLs to. You mentioned that you found a potential solution, how does it differ from Michael's approach?

**Comment by Aamani118** [comment]
> @QingsongYao I am in the same boat where I have a list of items that I would like to associate dynamic URLs to. You mentioned that you found a potential solution, how does it differ from Michael's approach?

Hi Im also same boat did find out the solution
