### ISSUE TITLE
smashing start silently does nothing

### ISSUE THREAD

**Issue by ibrewster** [Smashing/smashing#49]
I installed smashing on an OpenBSD 6.0 system with ruby 2.3.1, node JS version 4.4.5. I ran `gem install smashing` as per the getting started guide. However, when I run `smashing start`, nothing happens. The command returns immediately, with no indication that it did anything, and looking at the process list shows nothing. How can I debug this?

**Comment by ibrewster** [comment]
Turns out I had to specify the jobs path on the command line to get it to start.

**Comment by kinow** [comment]
Thanks for updating / closing the ticket.
