### ISSUE TITLE
Document how to deploy Smashing to AWS

### ISSUE THREAD

**Issue by kinow** [Smashing/smashing#54]
Found this repo https://github.com/popanything/dashing-beanstalk, but I need to deploy one dashboard to an Elastic Beanstalk, so will create a Wiki page for that and close the issue after that.

If anyone has experience on deploying to EC2, EB, etc, feel free to chime in :-)

**Comment by kinow** [comment]
Useful ref

* https://aws.amazon.com/blogs/developer/deploying-ruby-applications-to-aws-elastic-beanstalk-with-git/

**Comment by t0mtaylor** [comment]
what about http://sachinparmarblog.com/displaying-your-jamf-pro-casper-suite-stats-in-a-dashboard/

**Comment by kinow** [comment]
That's good as well @t0mtaylor thanks for sharing the link.

I successfully installed Dashing to Elastic Beanstalk,without needing to do anything on the AWS side. Your link contains more detailed steps for setting up an EC2 instance with Windows. We probably won't be able to cover all steps for all environments (e.g. EC2 with Ubuntu, EC2 with Amazon default AMI, EC2 with Windows, etc.)

So I am thinking about covering just the configuration required for Smashing. If none, then add a note saying that no further customization of Smashing was necessary with a specific set up in AWS.
