### ISSUE TITLE
Why build Ruby from source in Ubuntu installation guide

### ISSUE THREAD

**Issue by webmaster128** [Smashing/smashing#57]
In the installation guide for Ubuntu (https://github.com/Smashing/smashing/wiki/How-to%3A-Install-Smashing-on-Ubuntu-16.04.1), Ruby is build from source. Is there any very good reason to do so?

On 16.04, we can install Ruby 2.3.x by just saying `sudo apt-get install ruby`. Doing so ensures that
* All users get security updates
* The documentation does not get outdated
* Installation is way faster
* We don't risk breaking the system
* We don't need the scary list of pre-reqs but let Ubuntu do the dependency resolution

**Comment by kinow** [comment]
+1 @webmaster128 

Would you have time to send an updated version of the page? I'm using Ubuntu too (16.04.2) and installed via `apt install ruby`, so can't see why one would have to build ruby from source.

**Comment by webmaster128** [comment]
Okay, thanks for feedback. I am currently reworking the page. I think this will end up in a very generic tutorial for all Ubuntu versions

**Comment by webmaster128** [comment]
Updates the Ubuntu installation guide (tested Ubuntu 14.04 and 16.04):

https://github.com/Smashing/smashing/wiki/How-to%3A-Install-Smashing-on-Ubuntu

Could you have a look?

The only thing I wonder is: does it make sense to manually install widget feature gems manually via command line? Don't they belong in the project's Gemfile? For now I left the "Optional gems (adding functionality to Smashing widgets)" section unchanged but it may be better to remove it entirely.

**Comment by kinow** [comment]
@webmaster128 followed the tutorial in an empty Docker container (

* Skipped the optional step
* `cd MY_PROJECT` fails, as smashing creates the new directory actually with name my_project, all lower case (I wasn't aware of that :-) )

Everything OK, successfully started smashing :-) :+1:  kudos!

**Comment by webmaster128** [comment]
Fine :)

> Skipped the optional step

Okay I removed the optional installation to simplify the getting started guide. Additional gems for specific widgets should be covered on other wiki pages as those are not Ubuntu specific instructions.

> fails, as smashing creates the new directory actually with name my_project, all lower case (I wasn't aware of that :-) )

I was having the issue too when I quickly copy/pasted everything for testing. Hoever, changing the text to lower case is not the right solution I think, because of

> Replace all UPPER_CASE text with your details.

Maybe we should remove the PLACEHOLDER note entirely, rename the sample project to my_sample_dashboard and assume people understand they can put their name in here.

**Comment by kinow** [comment]
>Maybe we should remove the PLACEHOLDER note entirely, rename the sample project to my_sample_dashboard and assume people understand they can put their name in here.

:+1:

**Comment by webmaster128** [comment]
okay, all integrated
