### ISSUE TITLE
Cannot create custom actions

### ISSUE THREAD

**Issue by jhaagmans** [Smashing/smashing#58]
Hi,

For authentication, I'd like to serve users a separate page, but I seem unable to define a custom action. Instead, it tries to load a dasboard with the name of my custom action (and returns an error because it can't find it). This is an example of a simpe `config.ru` file for reproduction purposes:

```
require 'dashing'

configure do
  set :auth_token, 'YOUR_AUTH_TOKEN'

  helpers do
    def protected!
      # Put any authentication code you want in here.
      # This method is run before accessing any resource.
    end
  end

  get '/bla' do
    'bla'
  end
end

map Sinatra::Application.assets_prefix do
  run Sinatra::Application.sprockets
end

run Sinatra::Application
```

What am I missing?

**Comment by chrisjones** [comment]
If you create a bla.erb file in the dashboards directory containing your html/css/etc, this would work; however, I recommend placing your login form in a separate directory to maintain logical separation.

This has worked for me many times. Use:
```
  get '/auth/login' do
    erb :'auth/login'
  end
```

Then under your Dashboards directory, create a directory named 'auth' containing a file named 'login.erb'. Put your html (form post)/css/etc. in there.

**Comment by jhaagmans** [comment]
Thanks Chris. It's not an actual page, it's the oauth callback, so I don't want to render any erb files. I also realised what the real issue is: `app.rb` from dashing is loaded before the stuff in `config.ru`, meaning the route for `/:dashboard` takes precedence over all custom routes that are directly under the root. Namespacing the action fixed this. Cheers!
