### ISSUE TITLE
Why is bundler not a dependency of smashing?

### ISSUE THREAD

**Issue by webmaster128** [Smashing/smashing#59]
I installed smashing via `gem install smashing`. Now I created a project and ran `smashing start` (This succeeds with return code 0, which is a bug IMO), which does nothing because I did not install the Gems of my project's Gemfile.

In oder to install the project's dependencies I need bundler and I wonder why this was not installed automatically when installing the smashing gem. Is there a use case where we can use smashing without bundler?

**Comment by kinow** [comment]
I normally have `bundler` installed for other projects. For me it is like `pip` for Python, or `Maven` for Java. So more like a build tool rather than a project dependency (though it would be valid to say some projects depend on build tools as libraries, but I think it's not our case).

From [Bundler's website](http://bundler.io/):

>Bundler provides a consistent environment for Ruby projects by tracking and installing the exact gems and versions that are needed. 

Does that help @webmaster128 ?

**Comment by webmaster128** [comment]
Agree in general, but my point is: bundler is needed to **use** smashing. Even on systems that are no developer machines, you need to be able to run `bundle install` to install widget dependencies.

So the dependency for a user of the dashboard looks like

```
rubygems ~ pip ~ Maven        git/tarbar
 |                                |
 |  installs                      | copies
 v                                v
smashing                 dashboard project
         \             /
          \           /
           \         /
            \       /
        unusable dashboard
                |
                | requires bundler
                v
        usable dashboard
```

So I would not call it a build tool or development dependency but a runtime dependency.

**Comment by kinow** [comment]
Yup, good point. We could include - if not already - to the project requirements or prerequisites. Others would be a version of Ruby, plus all required runtime gem dependencies.

**Comment by tylermauthe** [comment]
This makes no sense. You can't include the package manager as a dependency because the package manager is required to download dependencies.
