### ISSUE TITLE
Document how to log to a file appender

### ISSUE THREAD

**Issue by kinow** [Smashing/smashing#61]
Would be nice to give an overall guide to users on how they could log - specially from jobs - to external files. This way it would be easier to manage smashing service, rotate logs, etc.

A sysadmin just asked me that, and I noticed all my jobs have always logged to stdout.

**Comment by bodsch** [comment]
i found an small logger class that i used for my jobs.
but i think, it is a better way, when a general log class is usable.
like this one: https://github.com/rocketjob/semantic_logger
profit: logging to elk or graylog included
