### ISSUE TITLE
Delete Dashing releases in Github

### ISSUE THREAD

**Issue by webmaster128** [Smashing/smashing#62]
In the Github project smashing, there are a lot of releases, that are no smashing releases but Dashing releases: https://github.com/Smashing/smashing/releases

I found this very confusing when I tried to find those releases in Rubygems, [where we only have 1.0.0](https://rubygems.org/gems/smashing).

Could you please delete those releases?

Maybe the tags should be deleted as well since those will conflict with future Smahing version tags but I am not quite sure here.

**Comment by kinow** [comment]
+1, since we renamed the gem and our releases are not related to those from dashing. If there's no objections, I will remove these this weekend.

**Comment by kinow** [comment]
Done. Removed all old releases for Dashing.

We have a gem uploaded on the 23rd October 2016 https://rubygems.org/gems/smashing/versions/1.0.0

So I found the last commits around that date regarding the 1.0.0 release, and manually added a tag. We can have another task later to automate the creation of the tag and update the docs.

Thanks!
Bruno

**Comment by webmaster128** [comment]
Thanks.

Just FYI and to avoid surprising effects: Checkouts of this repo that already downloaded the tags you now removed will keep then locally. Do not expect a removal by pulling. If there is a long living checkout where tags are relevant, you need to delete them manually or do a fresh checkout.

**Comment by kinow** [comment]
I wonder if `git fetch -p` would remove the removed tags?

**Comment by webmaster128** [comment]
Ah nice. Maybe that works, never tried that command.
