### ISSUE TITLE
Ubuntu errors on Smashing exit

### ISSUE THREAD

**Issue by howardsternisbatman** [Smashing/smashing#63]
Hello,

Everything works perfectly, however, when I quit the smashing server in the console I get a bunch of errors.  Not sure what it all means or how to solve it.

`^C/home/administrator/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/smashing-1.0.0/lib/dashing/cli.rb:89:in `system': Interrupt
        from /home/administrator/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/smashing-1.0.0/lib/dashing/cli.rb:89:in `run_command'
        from /home/administrator/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/smashing-1.0.0/lib/dashing/cli.rb:64:in `start'
        from /home/administrator/.rvm/gems/ruby-2.1.0@global/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/administrator/.rvm/gems/ruby-2.1.0@global/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/administrator/.rvm/gems/ruby-2.1.0@global/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/administrator/.rvm/gems/ruby-2.1.0@global/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/administrator/.rvm/gems/ruby-2.1.0@global/gems/smashing-1.0.0/bin/smashing:9:in `<top (required)>'
        from /home/administrator/.rvm/rubies/ruby-2.1.0/bin/smashing:23:in `load'
        from /home/administrator/.rvm/rubies/ruby-2.1.0/bin/smashing:23:in `<main>'
        from /home/administrator/.rvm/gems/ruby-2.1.0@global/bin/ruby_executable_hooks:15:in `eval'
        from /home/administrator/.rvm/gems/ruby-2.1.0@global/bin/ruby_executable_hooks:15:in `<main>'
`

**Comment by kinow** [comment]
I **think** I have similar errors, but assume these are normal errors. Like as when you stop a process in Python and get an interruption exception. Leaving it open, as it could be something else. But if I get a chance to work on this, will start investigating how to handle signals and nicely stop everything and say Good Bye to the user :-) 

Thanks for reporting this
Bruno

**Comment by tylermauthe** [comment]
Fixed by #67
