### ISSUE TITLE
Not saving to history.yml when using smashing start -d

### ISSUE THREAD

**Issue by yasa1987** [Smashing/smashing#70]
Hello, it's the same issue than in Dashing (https://github.com/Shopify/dashing/issues/244) and that was fixed into Dashing-Contrib (https://github.com/Shopify/dashing/pull/268)

Could you import this feature ? As you mentionned here (https://github.com/QubitProducts/dashing-contrib/issues/40) that dashing-contrib is not compatible I don't want to install it and break everything...

I'm not a Ruby developer otherwise I'd do it myself and send a patch
Thanks in advance

**Comment by yasa1987** [comment]
Uh I did found something by myself  : the example init.d script I found kills the process with a 9 (SIGKILL) signal instead of a 2 (SIGINT) signal. It explains everything.

Here is the the working init.d script you'd add into the documentation:
`#!/bin/bash
### BEGIN INIT INFO
# Provides: dashboard
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start daemon at boot time
# Description: Enable service provided by daemon.
### END INIT INFO

#set -e

# Must be a valid filename
NAME=smashing
DASHING_DIR=/opt/smashing-dashboards/tvs_dashboard
DAEMON=/usr/local/bin/smashing
PIDFILE="/var/run/smashing.pid"
DAEMON_OPTS="start -d -P $PIDFILE"
GEM_HOME=/var/lib/gems/2.1.0

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

case "$1" in
start)
echo -n "Starting daemon: ${NAME} "
start-stop-daemon --start --quiet --chdir $DASHING_DIR --exec $DAEMON -- $DAEMON_OPTS
echo "."
;;
stop)
echo -n "Stopping daemon: ${NAME} "
start-stop-daemon --stop --quiet --signal 2 --oknodo --pidfile $PIDFILE
echo "."
;;
restart)
start-stop-daemon --stop --quiet --signal 2 --oknodo --retry 30 --pidfile $PIDFILE
start-stop-daemon --start --quiet --chdir $DASHING_DIR --exec $DAEMON -- $DAEMON_OPTS
echo "."
;;

*)
echo "Usage: $1 {start|stop|restart}"
exit 1
esac

exit 0
`

**Comment by tylermauthe** [comment]
100% agreed, we are lacking hugely on operational documentation. We've got outstanding issues to create packages for various OS's, which would negate the need for lots of docs (beyond install instructions).

That being said, feel free to add our example init script to the wiki for now. Closing issue, thanks for the info!
