### ISSUE TITLE
Event Stream streaming data for all dashboards

### ISSUE THREAD

**Issue by dstuessy** [Smashing/smashing#71]
Hi, 

A dashboard I'm supporting has more than one -- even 10 or more.

The problem I'm facing is that the event stream for each dashboard seems to be including data for other dashboards. This makes the event stream 2MB.

Is there a way to limit the event stream data to only include data for the dashboard its streaming to?

I tried looking around for documentation on event streams but can't seem to find anything.

Many Thanks!

**Comment by tyler-mauthe-hs** [comment]
Hey @dstuessy -- you are totally correct and this is a known scalability issue with Smashing. There is currently no way to do this.

#48 is an attempt to fix it, you could try this out and see if it works for you. However, it will require you to modify the way you send events in your jobs if you take this approach.

I am thinking the correct approach involves combining a few initiatives:
- move to websockets
- add a pub/sub protocol on top of websockets
- widgets declare which streams of events they consume
- have the client parse all widgets in the dashboard
- clients should subscribe to topics declared in the widgets and update them

**Comment by dstuessy** [comment]
Thanks a lot for your fast reply @tyler-mauthe-hs! 

I agree that moving to websockets would be the right approach. Are there any plans in the works for this? 

For the time being I can see if the #48 is good enough. Unfortunately, though, it seems like I'll have to edit the gem itself? I'm still new to Ruby, so please bare with me.

**Comment by dstuessy** [comment]
Sorry to spam, but I had a thought.

I suppose I could add a new route to the `config.ru` file in my project root, without affecting the gem contents.

**Comment by tylermauthe** [comment]
@dstuessy - There are plans, but time is limited and my plans are many.

I also want to support Puma -- which would mean we'll have to hijack the socket and pass to something like Celluloid:
https://stackoverflow.com/questions/13886426/sinatra-websocket-celluloid

Adding routes to `config.ru` should work though! I'm going to close this issue, feel free to re-open if you run into issues with the customization though.
