### ISSUE TITLE
Smashing with Openhab and MQTT

### ISSUE THREAD

**Issue by nbibin001** [Smashing/smashing#74]
Hello, I was trying to use the Smashing dashboard with OpenHAB MQTT service. I have the OpenHAB running on a raspberry Pi and it is also working as an MQTT server. And I have few ESP8266 based wireless devices subscribes and publishes to topics with the MQTT server. So with this setup I am able to control the devices using the OpenHAB App from by phone. Now I was trying to use the nice dashboard (Dashing/Smashing) on my tablet and wanted to control the devices. I found an example in the below lik which works with Dashing + OpenHAB + REST API. So I was wondering if anybody really tried the MQTT combination instead of REST ? Really appreciate your help and suggestion. Kindly let me know if you need more details about what I am trying to do.

https://github.com/smar000/openhab-dashboard

**Comment by tylermauthe** [comment]
I don't know how MQTT works, but it if there's a ruby library for it then you should be able to make it work.

Note that Smashing is primarily designed around a "pull based" model - so having devices push into it isn't really ideal. There is an HTTP API that lets you push into it, but it's very rudimentary and not extensible.

**Comment by dnsmichi** [comment]
I've played around with this one, and it works really nice. A few modifications for a clean configuration file would be needed though.

https://gist.github.com/jmb/ac36d16a5180c3d2032a
