### ISSUE TITLE
Defining additional batman.js filters

### ISSUE THREAD

**Issue by mdehaas** [Smashing/smashing#75]
Hi all,

I have created a custom batman.js filter. This is now defined in '/var/lib/gems/2.3.0/gems/dashing-1.3.7/javascripts/dashing.coffee'. **Is there a way to define this in the dashboard files without changing the installed software**? I have tried to add a javascript file in /assets/javascripts but that broke everything...
I would like to have everything in one place so we are able to move the dashboard easily without loosing stuff like this.

Custom filter (Coffeescript)
`Batman.Filters.shortenedBytes = (num) ->`
`  return num if isNaN(num)`
`  if num >= (1125899906842624)`
`    (num / 1125899906842624).toFixed(1) + 'PB'`
`  else if num >= (1099511627776)`
`    (num / 1099511627776).toFixed(1) + 'TB'`
`  else if num >= (1073741824)`
`    (num / 1073741824).toFixed(1) + 'GB'`
`  else if num >= (1048576)`
`    (num / 1048576).toFixed(1) + 'MB'`
`  else if num >= (1024)`
`    (num / 1024).toFixed(1) + 'KB'`
`  else`
`    (num).toFixed(1) + 'B'`

**Comment by tylermauthe** [comment]
You could create a Widget named "util" or similar and clear out the HTML and CSS and put stuff like this into the coffescript file - just delete the normal widget stuff. Smashing just naively includes all of this stuff on boot into it's sprocket asset pipeline.
