### ISSUE TITLE
update ruby and/or gems

### ISSUE THREAD

**Issue by bodsch** [Smashing/smashing#79]
Currently, Smashing used many old ruby gems.
expectly rufus-scheduler in version 2.0.24. but this package is currently in version 3.4.2 available.

how can we plan a upgrade of modern ruby gem versions or ruby version too?

**Comment by olleolleolle** [comment]
When #65 is merged, things will be slightly newer.

The Travis CI matrix was just-now updated.

**Comment by tylermauthe** [comment]
Updated to 1.1.0 after merging some PRs.
