### ISSUE TITLE
Error: can't find gem smashing

### ISSUE THREAD

**Issue by hdalali** [Smashing/smashing#80]
I get following error message: when I execute $ smashing new my-project
```
/Users/xyz/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem smashing (>= 0.a) (Gem::GemNotFoundException)
	from /Users/xyz/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:299:in `activate_bin_path'
	from /Users/xyz/.rvm/gems/ruby-2.4.1/bin/smashing:23:in `<main>'
	from /Users/xyz/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/xyz/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

Any idea how to fix it? Thanks for the help in advance.

**Comment by kinow** [comment]
Did you install Smashing? Installing the Smashing gem, will add the `smashing` executable to your path.

See https://github.com/Smashing/smashing/wiki/How-to%3A-Install-Smashing-on-Ubuntu-or-Debian for installation instructions for Debian and Ubuntu. If you are using RHEL based distro, this issue may be helpful https://github.com/Smashing/smashing/issues/6

Closing as not an issue :+1:

**Comment by hdalali** [comment]
Thanks @kinow . Your instructions helped me to fix the issue. I am a budding engineer and I realized that I did not pay attention to the detail. Will pay more attention to detail and will do more ground work before posting a question going forward. Appreciate your support for young engineers like me.

**Comment by kinow** [comment]
Not a problem @hdalali . First time I used Dashing, I am quite sure I did exactly the same thing. And even now sometimes I jump to a server, fire `smashing new` and it takes a few moments for me to realize what happened when the command is not found :-)

Glad to help, hope to see your around again with questions/issues/pull requests. Should you have questions, you may find [our gitter channel](https://gitter.im/Smashing) a bit more helpful, as it may be faster to get an answer there.

Cheers
Bruno
