### ISSUE TITLE
A new release ?

### ISSUE THREAD

**Issue by gpatry** [Smashing/smashing#81]
Hy all,

When did you think a new release can be provided with the new pull request merged ?
Actually the gem is 1.0.0, perhaps a gem 1.0.1 or 1.1.0 could be built ?

So all users and boards can enjoy with the multiple enhancement ;-)

Thanks a lot for your great job !

**Comment by DandyDev** [comment]
Is this project dead? :(

**Comment by bodsch** [comment]
i hope not!

**Comment by tylermauthe** [comment]
Sure, I'll cut a release.
