### ISSUE TITLE
Error in first run

### ISSUE THREAD

**Issue by kaceo** [Smashing/smashing#82]
I just downloaded Smashing and built the first project.   Could not get past first error;

 $ smashing new myproject
 $ cd myproject
 $ bundle
 $ smashing start

/var/lib/gems/2.1.0/gems/execjs-2.0.2/lib/execjs/runtimes.rb:51:in `autodetect': Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
        from /var/lib/gems/2.1.0/gems/execjs-2.0.2/lib/execjs.rb:5:in `<module:ExecJS>'
        from /var/lib/gems/2.1.0/gems/execjs-2.0.2/lib/execjs.rb:4:in `<top (required)>'
        from /var/lib/gems/2.1.0/gems/backports-3.8.0/lib/backports/std_lib.rb:9:in `require'
        from /var/lib/gems/2.1.0/gems/backports-3.8.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /var/lib/gems/2.1.0/gems/coffee-script-2.2.0/lib/coffee_script.rb:1:in `<top (required)>'
        from /var/lib/gems/2.1.0/gems/backports-3.8.0/lib/backports/std_lib.rb:9:in `require'
        from /var/lib/gems/2.1.0/gems/backports-3.8.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /var/lib/gems/2.1.0/gems/coffee-script-2.2.0/lib/coffee-script.rb:1:in `<top (required)>'
        from /var/lib/gems/2.1.0/gems/backports-3.8.0/lib/backports/std_lib.rb:9:in `require'
        from /var/lib/gems/2.1.0/gems/backports-3.8.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /var/lib/gems/2.1.0/gems/smashing-1.0.0/lib/dashing/app.rb:5:in `<top (required)>'
        from /var/lib/gems/2.1.0/gems/smashing-1.0.0/lib/dashing.rb:3:in `require'
        from /var/lib/gems/2.1.0/gems/smashing-1.0.0/lib/dashing.rb:3:in `<top (required)>'
        from config.ru:1:in `require'
        from config.ru:1:in `block in <main>'
        from /var/lib/gems/2.1.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
        from /var/lib/gems/2.1.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /var/lib/gems/2.1.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `eval'
        from /var/lib/gems/2.1.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `load'
        from /var/lib/gems/2.1.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
        from /var/lib/gems/2.1.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:72:in `start'
        from /var/lib/gems/2.1.0/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
        from /var/lib/gems/2.1.0/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
        from /var/lib/gems/2.1.0/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
        from /usr/local/bin/thin:23:in `load'
        from /usr/local/bin/thin:23:in `<main>'

I also Gem install execjs and Gem install therubyrunner, same error.

**Comment by kaceo** [comment]
I figured out the solution.

I have to apt-get install nodejs

It would be nice if this step was given in the instruction and not "assumed".

**Comment by tylermauthe** [comment]
I have an open issue somewhere in the backlog to resolve this (#35). Sorry for the trouble! I'd prefer to not require nodejs to be installed - and if it is, I'd like to provide debian / yum packages as well as docker images.

**Comment by KuenzelIT** [comment]
I also had this problem just now. Anything new on not having to install nodejs?

**Comment by qume** [comment]
Still having this issue in 2021. On an embedded device it would be nice to either avoid this or install just the part needed (execjs?)

**Comment by kinow** [comment]
I agree @qume, but I still don't have a solution for this issue. There's a task to replace our current batman/coffee by Vue. While doing so, we could consider further changes in the architecture of Smashing so that users can still customize Smashing (i.e. install widgets, customize dashboard, etc) without needing the nodejs package (I **think** it's our coffeescript dependency that pulls it).
