### ISSUE TITLE
Windows client problem

### ISSUE THREAD

**Issue by mmarodin** [Smashing/smashing#83]
I've a problem using dashing from Windows clients.
It doesn't work, it seems that websocket it's not working, all counters are at 0 values.
I've tried with Firefox and Chrome, same issue, please see at the screenshot attached, done in a demo online.
My project and this online demo works correctly with Linux or OSX clients.

Does Dashing work with Windows client?
Please let me know, thanks.
Bye, Morgan

![dashing01](https://user-images.githubusercontent.com/2854369/29460519-8d3cf7b2-8428-11e7-9544-acb50529ac20.png)

**Comment by poflynn** [comment]
I don't think this is a Windows issue, we get this on some Macs but it works fine on our one windows machine. It seems to randomly work for some clients but not others. For our Macs for example, the OS & browser (Chrome) versions are identical, yet only 1 client machine out of 4 works. When we shutdown smashing it seems to 'flush' in some fashion as suddenly all the data appears on all clients but of course is no longer updated as the server is now off. Do you see this behavior also?

**Comment by mmarodin** [comment]
Yes, I can confirm that the behaviour is the same.
When I shutdown dashing it flush data to my browser, but the server is off.

Any suggestion to solve this issue?
Thanks, bye

**Comment by poflynn** [comment]
I have no clue how to fix this, deffo seems to be a bug. But I'd suggest you change the title of this issue.

I'm surprised more ppl aren't reporting it.

**Comment by tobias--** [comment]
I saw similar behavior running on a Windows Server. Can it be related to the installed ruby version?

**Comment by mmarodin** [comment]
I have ruby 2.0.0p648 and dashing (1.3.7)

**Comment by mmarodin** [comment]
And same problem in another server where is installed ruby 2.4.1p111

**Comment by xelprep** [comment]
Seeing this same behavior, almost exclusively on Macs (regardless of browser choice).  Any ideas on how to troubleshoot?
