### ISSUE TITLE
Newbie issue with ERB modifications

### ISSUE THREAD

**Issue by 1ncidental** [Smashing/smashing#84]
Hello all,

I have had several times where my dashboards have been working fine, then I make a modification to the erb file and my dashboard goes blank with nothing displayed.
The only resolution I have found is to recreate a new dashboard and start again.
Can you tell me if there is a service that I can restart?

Tried:
Reverting the changes
Restarting Smashing
Reboot
Bundler

Is it a problem with the job or the scheduler? Is there a way to restart or reset this?

**Comment by dfbm** [comment]
Are you sure that the new ERB file has no errors?
Have you tried copying a known-good version over it and reloading the page?

**Comment by 1ncidental** [comment]
Unfortunately no, once it crashes not even the sample dashboard runs.
