### ISSUE TITLE
Call coffee-script function after send_event

### ISSUE THREAD

**Issue by KulowRainer** [Smashing/smashing#86]
I'm sending data-updates to my personal widget from a job with the send_event. This is working and the changes are visible in the widget.
Now I want the coffescript behind this widget to recognize the data change and execute some code lines.
How can I solve this problem? Maybe with the 'onData'? I can't get this working.

**Comment by tylermauthe** [comment]
Yes, you can use `onData` - if your widget has a property called `onData` which is a function, it will trigger whenever new data is received by the widget (ie: whenever you send data with `send_event`).
