### ISSUE TITLE
Editing clock.coffee to display two different timezones

### ISSUE THREAD

**Issue by christianhau** [Smashing/smashing#87]
Hi!

I am trying to add one more timezone to the clock widget to display it on my dashboard. My goal is to add Indian (Delhi) time to the same widget.

I have changed clock.coffee and clock.html, but as I am new to Smashing and to Javascript I am apparently doing something wrong. Currently the widget only shows local time and nothing else. As I can't see any error messages I am unable to see where or what I am doing wrong, any help is appreciated!

**clock.coffee**
```
class Dashing.Clock extends Dashing.Widget

  ready: ->
    setInterval(@startTime, 500)

  startTime: =>
    today = new Date()
    todayindia = new Date(utc + (19800000*3600000))
    hindia = todayindia.getHours()
    mindia = todayindia.getMinutes()
    sindia = todayindia.getSeconds()
    mindia = @formatTime(mindia)

    h = today.getHours()
    m = today.getMinutes()
    s = today.getSeconds()
    m = @formatTime(m)
    s = @formatTime(s)
    @set('time', h + ":" + m + ":" + s)
    @set('date', today.toDateString())
    @set('timeindia', hindia + ":" + mindia + ":" + s)

  formatTime: (i) ->
    if i < 10 then "0" + i else i
```

**clock.html**

```
<h1 data-bind="date"></h1>
<h2 data-bind="time"></h2>
<h2 data-bind="timeindia"></h2>
```

**Comment by howardsternisbatman** [comment]
Hello,

I have 3-timezones on one widget.  Take a look at the attached, it should be close to what you are looking for.

This in your .erb will load the attached (once you unzip to your widgets folder.



[clock.zip](https://github.com/Smashing/smashing/files/1391781/clock.zip)

`<li data-row="1" data-col="1" data-sizex="2" data-sizey="2"><div data-id="clock" data-view="Clock" data-second-time-offset="-1" data-third-time-offset="-3"></div><i class="fa fa-calendar icon-background2"></i></li>`

Enjoy!

**Comment by christianhau** [comment]
Thanks! That worked like magic :)
