### ISSUE TITLE
Widget does not appear on dashboard

### ISSUE THREAD

**Issue by AlexArthur93** [Smashing/smashing#88]
Let me preface this by noting I'm very in experienced with Smashing and this is my first time working on it.

I have created a dashboard and successfully modified a selection of widgets. I am attempting to add the wunderlist widget listed under additional widgets and while no errors are outputted to the console the widget does not display. 

Hopefully someone has had this issue before but if not I'm looking for some debugging tips to get this widget displaying.

**Comment by howardsternisbatman** [comment]
Can you post the contents of your .erb file? Which widget exactly are you trying to implement, Wunderlist is listed x2 on the additional widgets page.

**Comment by AlexArthur93** [comment]
Thanks for taking the time to respond.

I actually fixed this problem just before I left work last night. The example implementation of the widget's page was incorrect.

It had as the example to paste into the .erb file: 
```

<li data-row="1" data-col="1" data-sizex="6" data-sizey="6">
  		<div data-id="wunderlist" data-view="wunderlist" ></div>
	</li>
```
However the it should have been 

```

<li data-row="1" data-col="1" data-sizex="6" data-sizey="6">
  		<div data-id="wunderlist" data-view="Wunderlist" ></div>
	</li>
```
to actually reference the correct files.
