### ISSUE TITLE
Widget Flickering

### ISSUE THREAD

**Issue by AlexArthur93** [Smashing/smashing#89]
Widgets that recieve a dynamic amount of data such as my to-do lists and various tables flicker on every update as it seems each indivual item is updated 1by1. Is there any way preventing or minimising this flickering?

**Comment by AlexArthur93** [comment]
Ended up saving the data that was being sent and only sent data through to the widget when the data changed. This lower the amount of flickering but not reduce it completely. Luckily I'm switching dashboards which minimises seeing the flickering even more but if there was a more concrete way of getting rid of the flickering It'd be real nice.

**Comment by tylermauthe** [comment]
This is a known issue with Batman.js - one of the main reasons we need to move to something faster like React or Vue. Your solution is about as good as it gets without re-implementing the component.

**Comment by AlexArthur93** [comment]
Thanks for clarifying.
