### ISSUE TITLE
opentsdb.rb Collection error

### ISSUE THREAD

**Issue by sbpr** [Smashing/smashing#90]
While using the opentsdb.rb job I am getting the error below in the console logs. has anyone seen an issue like this before?

scheduler caught exception:
Timeout::Error
/usr/lib/ruby/1.9.1/net/protocol.rb:146:in `rescue in rbuf_fill'
/usr/lib/ruby/1.9.1/net/protocol.rb:140:in `rbuf_fill'
/usr/lib/ruby/1.9.1/net/protocol.rb:122:in `readuntil'
/usr/lib/ruby/1.9.1/net/protocol.rb:132:in `readline'
/usr/lib/ruby/1.9.1/net/http.rb:2563:in `read_status_line'
/usr/lib/ruby/1.9.1/net/http.rb:2552:in `read_new'
/usr/lib/ruby/1.9.1/net/http.rb:1320:in `block in transport_request'
/usr/lib/ruby/1.9.1/net/http.rb:1317:in `catch'
/usr/lib/ruby/1.9.1/net/http.rb:1317:in `transport_request'
/usr/lib/ruby/1.9.1/net/http.rb:1294:in `request'
/usr/lib/ruby/1.9.1/net/http.rb:1287:in `block in request'
/usr/lib/ruby/1.9.1/net/http.rb:746:in `start'
/usr/lib/ruby/1.9.1/net/http.rb:1285:in `request'
/root/smashing-dashboards/my_project/jobs/opentsdb.rb:41:in `query'
/root/smashing-dashboards/my_project/jobs/opentsdb.rb:48:in `points'
/root/smashing-dashboards/my_project/jobs/opentsdb.rb:71:in `block (2 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
===================================================================

opentsdb.rb

# Too many decimals makes messy widgets
class Float
    def sigfig_to_s(digits)
        f = sprintf("%.#{digits - 1}e", self).to_f
        i = f.to_i
        (i == f ? i : f)
    end
end

class OpenTSDB
    # Initialize the class
    def initialize(host, port)
        @host = host
        @port = port
    end

    # Use OpenTSDB api to query for the stats, parse the returned JSON and return the result
    def query(statname, since=nil)
        since ||= '1m-ago'
        http = Net::HTTP.new(@host, @port)
        response = http.request(Net::HTTP::Get.new("/api/query?start=#{since}&m=#{statname}"))
        result = JSON.parse(response.body, :symbolize_names => true)
        return result.first
    end

    # Gather the datapoints and turn into Dashing graph widget format
    def points(name, since=nil)
        stats = query name, since
        dps = stats[:dps]

        points = []
        last = 0
        count = 1

        (dps.select { |el| not el.nil? }).each do|item|
            points << { x: count, y: item[1].sigfig_to_s(2) }
            count += 1
            last = item[1].sigfig_to_s(2)
        end

        return points, last
    end
end

job_mapping.each do |title, statname|
   SCHEDULER.every '10s', :first_in => 0 do
        # Create an instance of our opentsdb class
        q = OpenTSDB.new OPENTSDB_HOST, OPENTSDB_PORT

        # get the current points and value. Timespan is static atm
        points, current = q.points "#{statname}", "1m-ago"

        # send to dashboard, so the number the meter and the graph widget can understand it
        send_event "#{title}", { current: current, value: current, points: points }
   end
end

**Comment by tylermauthe** [comment]
Sorry this isn't related to Smashing core. Please reach out to the makers of the `OpenTSDB` ruby gem or the creator of that job.
