### ISSUE TITLE
Connection to a MantisBT SOAP API using Smashing

### ISSUE THREAD

**Issue by reegen** [Smashing/smashing#98]
Hi, 
Is it possible to connect to a MantisBT SOAP API using Smashing?
It would be very nice if I could retrive data from my Mantis Webservices.
Thanks in advance!

**Comment by bodsch** [comment]
you can wrote your own lib/job to pull data prom MantisBT.
for example, [savon](http://savonrb.com/version2/) is an  SOAP gem for ruby.
