### ISSUE TITLE
start at boot

### ISSUE THREAD

**Issue by azazzel** [Smashing/smashing#99]
spend couple of hours trying to figure it out how to start at boot using the Init.d. No luck, anyone care to help me with this?

**Comment by mdehaas** [comment]
I have this running on Debian. I’ll check tomorrow when I’m in the office.

**Comment by tylermauthe** [comment]
GitHub issues is not a place for Linux technical support, as stated in the [CONTRIBUTING.d](https://github.com/Smashing/smashing/blob/master/CONTRIBUTING.md#have-an-issue) (which you are asked to read before posting) you should ask questions like that in our Gitter chat room.

If you're on Ubuntu, you need update rc.d:
http://manpages.ubuntu.com/manpages/precise/man8/update-rc.d.8.html

If you're on CentOS, you need chkconfig:
https://www.centos.org/docs/5/html/Deployment_Guide-en-US/s1-services-chkconfig.html

If you're on a modern distro that uses systemd, you need to use sysctl:
https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units
